; Generated by PHP86 v1.0 (2026-03-05)
; Source : SAMPLES\PHP\array.php
; Cible  : 8086 DOS (.MODEL SMALL)
; Pile   : 1024 octets

        .MODEL  SMALL
        .STACK  1024

_TEXT   SEGMENT PUBLIC 'CODE'
        ASSUME  CS:_TEXT

; Point d'entree programme PHP86
_PHF_main:
	MOV	AX, @DATA
	MOV	DS, AX
	MOV	AX, SS
	MOV	ES, AX

; -- Code PHP traduit ---

; echo
	MOV	AX, OFFSET _PHK_3
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $nums [BP-2]
	SUB	SP, 2
	MOV	AX, OFFSET _PHK_ARR3
	MOV	[BP-2], AX
; echo
	MOV	AX, OFFSET _PHK_5
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
	MOV	SI, AX
	MOV	AX, [SI]
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_7
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
	MOV	SI, AX
	MOV	AX, 0
	MOV	BX, AX
	SHL	BX, 1
	MOV	AX, [SI+BX+2]
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
	MOV	SI, AX
	MOV	AX, 1
	MOV	BX, AX
	SHL	BX, 1
	MOV	AX, [SI+BX+2]
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_9
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
	MOV	SI, AX
	MOV	AX, 4
	MOV	BX, AX
	SHL	BX, 1
	MOV	AX, [SI+BX+2]
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_10
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
; local $__feB11 [BP-2]
	SUB	SP, 2
; local $__feI11 [BP-2]
	SUB	SP, 2
; local $__feE11 [BP-2]
	SUB	SP, 2
; foreach : init
	MOV	SI, AX
	MOV	AX, [SI]
	MOV	[BP-8], AX
	INC	SI
	INC	SI
	MOV	AX, SI
	MOV	[BP-4], AX
	XOR	AX, AX
	MOV	[BP-6], AX
; local $v [BP-2]
	SUB	SP, 2
_PHL_FETOP_12:
; foreach : test fin de tableau
	MOV	AX, [BP-6]
	MOV	BX, AX
	MOV	AX, [BP-8]
	CMP	BX, AX
	JAE	_PHL_FEEND_13
; foreach : charger arr[idx]
	MOV	AX, [BP-4]
	MOV	SI, AX
	MOV	AX, [BP-6]
	SHL	AX, 1
	MOV	BX, AX
	MOV	AX, [SI+BX]
	MOV	[BP-10], AX
; echo
	MOV	AX, [BP-10]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_15
	MOV	SI, AX
	CALL	_PHRT_PRINT
_PHL_FECONT_14:
; foreach : incrementer index
	MOV	AX, [BP-6]
	INC	AX
	MOV	[BP-6], AX
	JMP	_PHL_FETOP_12
_PHL_FEEND_13:
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_16
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
; local $__feB17 [BP-2]
	SUB	SP, 2
; local $__feI17 [BP-2]
	SUB	SP, 2
; local $__feE17 [BP-2]
	SUB	SP, 2
; foreach : init
	MOV	SI, AX
	MOV	AX, [SI]
	MOV	[BP-16], AX
	INC	SI
	INC	SI
	MOV	AX, SI
	MOV	[BP-12], AX
	XOR	AX, AX
	MOV	[BP-14], AX
; local $k [BP-2]
	SUB	SP, 2
_PHL_FETOP_18:
; foreach : test fin de tableau
	MOV	AX, [BP-14]
	MOV	BX, AX
	MOV	AX, [BP-16]
	CMP	BX, AX
	JAE	_PHL_FEEND_19
; foreach : charger arr[idx]
	MOV	AX, [BP-12]
	MOV	SI, AX
	MOV	AX, [BP-14]
	SHL	AX, 1
	MOV	BX, AX
	MOV	AX, [SI+BX]
	MOV	[BP-10], AX
; foreach : cle (index)
	MOV	AX, [BP-14]
	MOV	[BP-18], AX
; echo
	MOV	AX, OFFSET _PHK_21
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-18]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_22
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-10]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_15
	MOV	SI, AX
	CALL	_PHRT_PRINT
_PHL_FECONT_20:
; foreach : incrementer index
	MOV	AX, [BP-14]
	INC	AX
	MOV	[BP-14], AX
	JMP	_PHL_FETOP_18
_PHL_FEEND_19:
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $somme [BP-2]
	SUB	SP, 2
	MOV	AX, 0
	MOV	[BP-20], AX
	MOV	AX, [BP-2]
; local $__feB23 [BP-2]
	SUB	SP, 2
; local $__feI23 [BP-2]
	SUB	SP, 2
; local $__feE23 [BP-2]
	SUB	SP, 2
; foreach : init
	MOV	SI, AX
	MOV	AX, [SI]
	MOV	[BP-26], AX
	INC	SI
	INC	SI
	MOV	AX, SI
	MOV	[BP-22], AX
	XOR	AX, AX
	MOV	[BP-24], AX
_PHL_FETOP_24:
; foreach : test fin de tableau
	MOV	AX, [BP-24]
	MOV	BX, AX
	MOV	AX, [BP-26]
	CMP	BX, AX
	JAE	_PHL_FEEND_25
; foreach : charger arr[idx]
	MOV	AX, [BP-22]
	MOV	SI, AX
	MOV	AX, [BP-24]
	SHL	AX, 1
	MOV	BX, AX
	MOV	AX, [SI+BX]
	MOV	[BP-10], AX
	MOV	AX, [BP-20]
	PUSH	AX
	MOV	AX, [BP-10]
	MOV	BX, AX
	POP	AX
	ADD	AX, BX
	MOV	[BP-20], AX
_PHL_FECONT_26:
; foreach : incrementer index
	MOV	AX, [BP-24]
	INC	AX
	MOV	[BP-24], AX
	JMP	_PHL_FETOP_24
_PHL_FEEND_25:
; echo
	MOV	AX, OFFSET _PHK_27
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-20]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $tmin [BP-2]
	SUB	SP, 2
	MOV	AX, [BP-2]
	MOV	SI, AX
	MOV	AX, 0
	MOV	BX, AX
	SHL	BX, 1
	MOV	AX, [SI+BX+2]
	MOV	[BP-28], AX
; local $tmax [BP-2]
	SUB	SP, 2
	MOV	AX, [BP-2]
	MOV	SI, AX
	MOV	AX, 0
	MOV	BX, AX
	SHL	BX, 1
	MOV	AX, [SI+BX+2]
	MOV	[BP-30], AX
	MOV	AX, [BP-2]
; local $__feB28 [BP-2]
	SUB	SP, 2
; local $__feI28 [BP-2]
	SUB	SP, 2
; local $__feE28 [BP-2]
	SUB	SP, 2
; foreach : init
	MOV	SI, AX
	MOV	AX, [SI]
	MOV	[BP-36], AX
	INC	SI
	INC	SI
	MOV	AX, SI
	MOV	[BP-32], AX
	XOR	AX, AX
	MOV	[BP-34], AX
_PHL_FETOP_29:
; foreach : test fin de tableau
	MOV	AX, [BP-34]
	MOV	BX, AX
	MOV	AX, [BP-36]
	CMP	BX, AX
	JAE	_PHL_FEEND_30
; foreach : charger arr[idx]
	MOV	AX, [BP-32]
	MOV	SI, AX
	MOV	AX, [BP-34]
	SHL	AX, 1
	MOV	BX, AX
	MOV	AX, [SI+BX]
	MOV	[BP-10], AX
	MOV	AX, [BP-10]
	PUSH	AX
	MOV	AX, [BP-28]
	MOV	BX, AX
	POP	AX
	CMP	AX, BX
	MOV	AX, 0
	SETL	AL
	TEST	AX, AX
	JZ	_PHL_ELSE_33
	MOV	AX, [BP-10]
	MOV	[BP-28], AX
_PHL_ELSE_33:
_PHL_ENDIF_32:
	MOV	AX, [BP-10]
	PUSH	AX
	MOV	AX, [BP-30]
	MOV	BX, AX
	POP	AX
	CMP	AX, BX
	MOV	AX, 0
	SETG	AL
	TEST	AX, AX
	JZ	_PHL_ELSE_35
	MOV	AX, [BP-10]
	MOV	[BP-30], AX
_PHL_ELSE_35:
_PHL_ENDIF_34:
_PHL_FECONT_31:
; foreach : incrementer index
	MOV	AX, [BP-34]
	INC	AX
	MOV	[BP-34], AX
	JMP	_PHL_FETOP_29
_PHL_FEEND_30:
; echo
	MOV	AX, OFFSET _PHK_36
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-28]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_37
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-30]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $fib [BP-2]
	SUB	SP, 2
	MOV	AX, OFFSET _PHK_ARR37
	MOV	[BP-38], AX
; echo
	MOV	AX, OFFSET _PHK_39
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-38]
	MOV	SI, AX
	MOV	AX, 0
	MOV	BX, AX
	SHL	BX, 1
	MOV	AX, [SI+BX+2]
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_40
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-38]
	MOV	SI, AX
	MOV	AX, 6
	MOV	BX, AX
	SHL	BX, 1
	MOV	AX, [SI+BX+2]
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_41
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-38]
	MOV	SI, AX
	MOV	AX, 7
	MOV	BX, AX
	SHL	BX, 1
	MOV	AX, [SI+BX+2]
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_42
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-38]
	MOV	SI, AX
	MOV	AX, [SI]
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $squares [BP-2]
	SUB	SP, 2
	MOV	AX, OFFSET _PHK_ARR42
	MOV	[BP-40], AX
; echo
	MOV	AX, OFFSET _PHK_44
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-40]
	MOV	SI, AX
	MOV	AX, 2
	MOV	BX, AX
	SHL	BX, 1
	MOV	AX, [SI+BX+2]
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_45
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-40]
	MOV	SI, AX
	MOV	AX, 4
	MOV	BX, AX
	SHL	BX, 1
	MOV	AX, [SI+BX+2]
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_46
	MOV	SI, AX
	CALL	_PHRT_PRINT

; -- Fin de programme --
	MOV	AX, 4C00h
	INT	21h


; ============================================================
; RUNTIME PHP86 -- TODO 22
; ============================================================

_PHRT_STRLEN:
        PUSH    BP
        MOV     BP, SP
        PUSH    SI
        MOV     SI, [BP+4]
        XOR     AX, AX
_PHRT_SL_LP:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_SL_DN
        INC     SI
        INC     AX
        JMP     _PHRT_SL_LP
_PHRT_SL_DN:
        POP     SI
        POP     BP
        RET

_PHRT_PRINT:
        PUSH    AX
        PUSH    BX
        PUSH    CX
        PUSH    DX
        PUSH    SI
        MOV     DX, SI
        XOR     CX, CX
_PHRT_PR_LN:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_PR_DN
        INC     SI
        INC     CX
        JMP     _PHRT_PR_LN
_PHRT_PR_DN:
        JCXZ    _PHRT_PR_RET
        MOV     AH, 40h
        MOV     BX, 1
        INT     21h
_PHRT_PR_RET:
        POP     SI
        POP     DX
        POP     CX
        POP     BX
        POP     AX
        RET

_PHRT_NEWLINE:
        PUSH    SI
        MOV     SI, OFFSET _PHRT_CRLF
        CALL    _PHRT_PRINT
        POP     SI
        RET

_PHRT_PRINTLN:
        CALL    _PHRT_PRINT
        CALL    _PHRT_NEWLINE
        RET

_PHRT_ITOA:
        PUSH    CX
        PUSH    DX
        PUSH    BX
        PUSH    DI
        MOV     DI, OFFSET _PHRT_IBUF
        MOV     SI, DI
        TEST    AX, AX
        JNS     _PHRT_IA_POS
        MOV     BYTE PTR [DI], 2Dh
        INC     DI
        NEG     AX
_PHRT_IA_POS:
        MOV     BX, 10
        XOR     CX, CX
_PHRT_IA_LP:
        XOR     DX, DX
        DIV     BX
        ADD     DL, 30h
        PUSH    DX
        INC     CX
        TEST    AX, AX
        JNZ     _PHRT_IA_LP
_PHRT_IA_POP:
        POP     DX
        MOV     [DI], DL
        INC     DI
        LOOP    _PHRT_IA_POP
        MOV     BYTE PTR [DI], 0
        POP     DI
        POP     BX
        POP     DX
        POP     CX
        RET

_PHRT_ATOI:
        PUSH    BP
        MOV     BP, SP
        PUSH    SI
        PUSH    BX
        PUSH    CX
        MOV     SI, [BP+4]
        XOR     AX, AX
        MOV     CX, 1
        CMP     BYTE PTR [SI], 2Dh
        JNE     _PHRT_AI_LP
        MOV     CX, -1
        INC     SI
_PHRT_AI_LP:
        MOV     BL, [SI]
        CMP     BL, 30h
        JB      _PHRT_AI_DN
        CMP     BL, 39h
        JA      _PHRT_AI_DN
        IMUL    AX, AX, 10
        SUB     BL, 30h
        XOR     BH, BH
        ADD     AX, BX
        INC     SI
        JMP     _PHRT_AI_LP
_PHRT_AI_DN:
        IMUL    AX, CX
        POP     CX
        POP     BX
        POP     SI
        POP     BP
        RET

_PHRT_CONCAT:
        PUSH    SI
        PUSH    BX
        MOV     BX, SI
_PHRT_CC_END:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_CC_CPY
        INC     SI
        JMP     _PHRT_CC_END
_PHRT_CC_CPY:
        MOV     AL, [DI]
        MOV     [SI], AL
        INC     SI
        INC     DI
        TEST    AL, AL
        JNZ     _PHRT_CC_CPY
        MOV     AX, BX
        POP     BX
        POP     SI
        RET

_PHRT_STREQ:
        PUSH    SI
        PUSH    DI
        PUSH    BX
_PHRT_SE_LP:
        MOV     AL, [SI]
        MOV     BL, [DI]
        CMP     AL, BL
        JNE     _PHRT_SE_NO
        TEST    AL, AL
        JZ      _PHRT_SE_YES
        INC     SI
        INC     DI
        JMP     _PHRT_SE_LP
_PHRT_SE_YES:
        MOV     AX, 1
        JMP     _PHRT_SE_DN
_PHRT_SE_NO:
        XOR     AX, AX
_PHRT_SE_DN:
        POP     BX
        POP     DI
        POP     SI
        RET

_PHRT_POWER:
        PUSH    BX
        PUSH    CX
        MOV     BX, AX
        MOV     AX, 1
        TEST    CX, CX
        JZ      _PHRT_PW_DN
_PHRT_PW_LP:
        IMUL    AX, BX
        LOOP    _PHRT_PW_LP
_PHRT_PW_DN:
        POP     CX
        POP     BX
        RET

_PHRT_ARRAY_PUSH:
        XOR     AX, AX
        RET

_PHRT_PANIC:
        CALL    _PHRT_PRINTLN
        MOV     AX, 4C01h
        INT     21h


_TEXT   ENDS

_DATA   SEGMENT PUBLIC 'DATA'
        ASSUME  DS:_DATA
_PHK_1:
        DB      13,10,0
_PHK_2:
        DB      87,73,78,51,50,0
_PHK_3:
        DB      61,61,61,32,97,114,114,97,121,46,112,104,112,32,61,61,61,10,0
_PHK_ARR3:
        DW      5
_PHK_ARR3_0:
        DW      10
_PHK_ARR3_1:
        DW      20
_PHK_ARR3_2:
        DW      30
_PHK_ARR3_3:
        DW      40
_PHK_ARR3_4:
        DW      50
_PHK_5:
        DB      84,97,105,108,108,101,32,32,32,32,32,32,32,32,32,58,32,0
_PHK_6:
        DB      10,0
_PHK_7:
        DB      80,114,101,109,105,101,114,32,32,32,91,48,93,32,32,58,32,0
_PHK_8:
        DB      68,101,117,120,105,101,109,101,32,32,91,49,93,32,32,58,32,0
_PHK_9:
        DB      67,105,110,113,117,105,101,109,101,32,91,52,93,32,32,58,32,0
_PHK_10:
        DB      102,111,114,101,97,99,104,32,118,97,108,115,32,32,32,58,32,0
_PHK_15:
        DB      32,0
_PHK_16:
        DB      102,111,114,101,97,99,104,32,107,61,62,118,32,32,32,58,32,0
_PHK_21:
        DB      91,0
_PHK_22:
        DB      93,61,0
_PHK_27:
        DB      83,111,109,109,101,32,32,32,32,32,32,32,32,32,32,58,32,0
_PHK_36:
        DB      77,105,110,32,32,32,32,32,32,32,32,32,32,32,32,58,32,0
_PHK_37:
        DB      77,97,120,32,32,32,32,32,32,32,32,32,32,32,32,58,32,0
_PHK_ARR37:
        DW      8
_PHK_ARR37_0:
        DW      1
_PHK_ARR37_1:
        DW      1
_PHK_ARR37_2:
        DW      2
_PHK_ARR37_3:
        DW      3
_PHK_ARR37_4:
        DW      5
_PHK_ARR37_5:
        DW      8
_PHK_ARR37_6:
        DW      13
_PHK_ARR37_7:
        DW      21
_PHK_39:
        DB      70,105,98,111,110,97,99,99,105,91,48,93,32,32,32,58,32,0
_PHK_40:
        DB      70,105,98,111,110,97,99,99,105,91,54,93,32,32,32,58,32,0
_PHK_41:
        DB      70,105,98,111,110,97,99,99,105,91,55,93,32,32,32,58,32,0
_PHK_42:
        DB      78,98,32,101,108,101,109,101,110,116,115,32,32,32,32,58,32,0
_PHK_ARR42:
        DW      5
_PHK_ARR42_0:
        DW      1
_PHK_ARR42_1:
        DW      4
_PHK_ARR42_2:
        DW      9
_PHK_ARR42_3:
        DW      16
_PHK_ARR42_4:
        DW      25
_PHK_44:
        DB      67,97,114,114,101,115,91,50,93,32,32,32,32,32,32,58,32,0
_PHK_45:
        DB      67,97,114,114,101,115,91,52,93,32,32,32,32,32,32,58,32,0
_PHK_46:
        DB      61,61,61,32,70,105,110,32,97,114,114,97,121,46,112,104,112,32,61,61,61,10,0
_PHRT_CRLF:
        DB      13,10,0
_PHRT_IBUF:
        DB      32,32,32,32,32,32,32,32,32,32,32,32,0
_DATA   ENDS

        END     _PHF_main
