; Generated by PHP86 v1.0 (2026-03-05)
; Source : SAMPLES\PHP\control.php
; Cible  : 8086 DOS (.MODEL SMALL)
; Pile   : 1024 octets

        .MODEL  SMALL
        .STACK  1024

_TEXT   SEGMENT PUBLIC 'CODE'
        ASSUME  CS:_TEXT

; Point d'entree programme PHP86
_PHF_main:
	MOV	AX, @DATA
	MOV	DS, AX
	MOV	AX, SS
	MOV	ES, AX

; -- Code PHP traduit ---

; echo
	MOV	AX, OFFSET _PHK_3
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $n [BP-2]
	SUB	SP, 2
	MOV	AX, 42
	MOV	[BP-2], AX
; echo
	MOV	AX, OFFSET _PHK_4
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-2]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_5
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
	CMP	AX, 100
	MOV	AX, 0
	SETG	AL
	TEST	AX, AX
	JZ	_PHL_ELSE_7
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
	JMP	_PHL_ENDIF_6
_PHL_ELSE_7:
	MOV	AX, [BP-2]
	CMP	AX, 10
	MOV	AX, 0
	SETG	AL
	TEST	AX, AX
	JZ	_PHL_ELSE_9
; echo
	MOV	AX, OFFSET _PHK_10
	MOV	SI, AX
	CALL	_PHRT_PRINT
	JMP	_PHL_ENDIF_6
_PHL_ELSE_9:
; echo
	MOV	AX, OFFSET _PHK_11
	MOV	SI, AX
	CALL	_PHRT_PRINT
_PHL_ENDIF_6:
; echo
	MOV	AX, OFFSET _PHK_12
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $i [BP-2]
	SUB	SP, 2
	MOV	AX, 1
	MOV	[BP-4], AX
_PHL_WHTOP_13:
	MOV	AX, [BP-4]
	CMP	AX, 5
	MOV	AX, 0
	SETLE	AL
	TEST	AX, AX
	JZ	_PHL_WHEND_14
; echo
	MOV	AX, [BP-4]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_15
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-4]
	ADD	AX, 1
	MOV	[BP-4], AX
	JMP	_PHL_WHTOP_13
_PHL_WHEND_14:
; echo
	MOV	AX, OFFSET _PHK_5
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_16
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $j [BP-2]
	SUB	SP, 2
	MOV	AX, 3
	MOV	[BP-6], AX
_PHL_DOTOP_17:
; echo
	MOV	AX, [BP-6]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_15
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-6]
	SUB	AX, 1
	MOV	[BP-6], AX
_PHL_DOCONT_19:
	MOV	AX, [BP-6]
	CMP	AX, 0
	MOV	AX, 0
	SETG	AL
	TEST	AX, AX
	JNZ	_PHL_DOTOP_17
_PHL_DOEND_18:
; echo
	MOV	AX, OFFSET _PHK_5
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_20
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, 0
; local $k [BP-2]
	SUB	SP, 2
	MOV	[BP-8], AX
_PHL_FORTOP_21:
	MOV	AX, [BP-8]
	CMP	AX, 5
	MOV	AX, 0
	SETL	AL
	TEST	AX, AX
	JZ	_PHL_FOREND_22
	JMP	_PHL_FORBODY_24
_PHL_FORINC_23:
	MOV	AX, [BP-8]
	INC	AX
	MOV	[BP-8], AX
	JMP	_PHL_FORTOP_21
_PHL_FORBODY_24:
; echo
	MOV	AX, [BP-8]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_15
	MOV	SI, AX
	CALL	_PHRT_PRINT
	JMP	_PHL_FORINC_23
_PHL_FOREND_22:
; echo
	MOV	AX, OFFSET _PHK_5
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_25
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, 0
; local $m [BP-2]
	SUB	SP, 2
	MOV	[BP-10], AX
_PHL_FORTOP_26:
	MOV	AX, [BP-10]
	CMP	AX, 10
	MOV	AX, 0
	SETL	AL
	TEST	AX, AX
	JZ	_PHL_FOREND_27
	JMP	_PHL_FORBODY_29
_PHL_FORINC_28:
	MOV	AX, [BP-10]
	INC	AX
	MOV	[BP-10], AX
	JMP	_PHL_FORTOP_26
_PHL_FORBODY_29:
	MOV	AX, [BP-10]
	CMP	AX, 3
	MOV	AX, 0
	SETE	AL
	TEST	AX, AX
	JZ	_PHL_ELSE_31
	JMP	_PHL_FOREND_27
_PHL_ELSE_31:
_PHL_ENDIF_30:
; echo
	MOV	AX, [BP-10]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_15
	MOV	SI, AX
	CALL	_PHRT_PRINT
	JMP	_PHL_FORINC_28
_PHL_FOREND_27:
; echo
	MOV	AX, OFFSET _PHK_5
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_32
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, 0
; local $p [BP-2]
	SUB	SP, 2
	MOV	[BP-12], AX
_PHL_FORTOP_33:
	MOV	AX, [BP-12]
	CMP	AX, 10
	MOV	AX, 0
	SETL	AL
	TEST	AX, AX
	JZ	_PHL_FOREND_34
	JMP	_PHL_FORBODY_36
_PHL_FORINC_35:
	MOV	AX, [BP-12]
	INC	AX
	MOV	[BP-12], AX
	JMP	_PHL_FORTOP_33
_PHL_FORBODY_36:
	MOV	AX, [BP-12]
	MOV	BX, 2
	CWD
	IDIV	BX
	MOV	AX, DX
	CMP	AX, 0
	MOV	AX, 0
	SETE	AL
	TEST	AX, AX
	JZ	_PHL_ELSE_38
	JMP	_PHL_FORINC_35
_PHL_ELSE_38:
_PHL_ENDIF_37:
; echo
	MOV	AX, [BP-12]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_15
	MOV	SI, AX
	CALL	_PHRT_PRINT
	JMP	_PHL_FORINC_35
_PHL_FOREND_34:
; echo
	MOV	AX, OFFSET _PHK_5
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $code [BP-2]
	SUB	SP, 2
	MOV	AX, 2
	MOV	[BP-14], AX
; echo
	MOV	AX, OFFSET _PHK_39
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-14]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_40
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-14]
; local $__swS41 [BP-2]
	SUB	SP, 2
	MOV	[BP-16], AX
; switch : init match flag DX=0
	XOR	DX, DX
; case
	MOV	AX, [BP-16]
	MOV	BX, AX
	CMP	BX, 1
	JNE	_PHL_CSNE_42
	MOV	DX, 1
_PHL_CSNE_42:
	TEST	DX, DX
	JZ	_PHL_CSKP_43
; echo
	MOV	AX, OFFSET _PHK_44
	MOV	SI, AX
	CALL	_PHRT_PRINT
	JMP	_PHL_SWEND_41
_PHL_CSKP_43:
; case
	MOV	AX, [BP-16]
	MOV	BX, AX
	CMP	BX, 2
	JNE	_PHL_CSNE_45
	MOV	DX, 1
_PHL_CSNE_45:
	TEST	DX, DX
	JZ	_PHL_CSKP_46
; echo
	MOV	AX, OFFSET _PHK_47
	MOV	SI, AX
	CALL	_PHRT_PRINT
	JMP	_PHL_SWEND_41
_PHL_CSKP_46:
; case
	MOV	AX, [BP-16]
	MOV	BX, AX
	CMP	BX, 3
	JNE	_PHL_CSNE_48
	MOV	DX, 1
_PHL_CSNE_48:
	TEST	DX, DX
	JZ	_PHL_CSKP_49
; echo
	MOV	AX, OFFSET _PHK_50
	MOV	SI, AX
	CALL	_PHRT_PRINT
	JMP	_PHL_SWEND_41
_PHL_CSKP_49:
; default
; echo
	MOV	AX, OFFSET _PHK_51
	MOV	SI, AX
	CALL	_PHRT_PRINT
_PHL_SWEND_41:
; local $a [BP-2]
	SUB	SP, 2
	MOV	AX, 1
	MOV	[BP-18], AX
; local $b [BP-2]
	SUB	SP, 2
	MOV	AX, 0
	MOV	[BP-20], AX
; echo
	MOV	AX, OFFSET _PHK_52
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-18]
	TEST	AX, AX
	JZ	_PHL_SCAND_53
	MOV	AX, [BP-20]
	TEST	AX, AX
	MOV	AX, 0
	SETNE	AL
_PHL_SCAND_53:
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_5
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_54
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-18]
	TEST	AX, AX
	JNZ	_PHL_SCOR_55
	MOV	AX, [BP-20]
	TEST	AX, AX
	MOV	AX, 0
	SETNE	AL
_PHL_SCOR_55:
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_5
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_56
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-18]
	TEST	AX, AX
	MOV	AX, 0
	SETE	AL
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_5
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_57
	MOV	SI, AX
	CALL	_PHRT_PRINT

; -- Fin de programme --
	MOV	AX, 4C00h
	INT	21h


; ============================================================
; RUNTIME PHP86 -- TODO 22
; ============================================================

_PHRT_STRLEN:
        PUSH    BP
        MOV     BP, SP
        PUSH    SI
        MOV     SI, [BP+4]
        XOR     AX, AX
_PHRT_SL_LP:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_SL_DN
        INC     SI
        INC     AX
        JMP     _PHRT_SL_LP
_PHRT_SL_DN:
        POP     SI
        POP     BP
        RET

_PHRT_PRINT:
        PUSH    AX
        PUSH    BX
        PUSH    CX
        PUSH    DX
        PUSH    SI
        MOV     DX, SI
        XOR     CX, CX
_PHRT_PR_LN:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_PR_DN
        INC     SI
        INC     CX
        JMP     _PHRT_PR_LN
_PHRT_PR_DN:
        JCXZ    _PHRT_PR_RET
        MOV     AH, 40h
        MOV     BX, 1
        INT     21h
_PHRT_PR_RET:
        POP     SI
        POP     DX
        POP     CX
        POP     BX
        POP     AX
        RET

_PHRT_NEWLINE:
        PUSH    SI
        MOV     SI, OFFSET _PHRT_CRLF
        CALL    _PHRT_PRINT
        POP     SI
        RET

_PHRT_PRINTLN:
        CALL    _PHRT_PRINT
        CALL    _PHRT_NEWLINE
        RET

_PHRT_ITOA:
        PUSH    CX
        PUSH    DX
        PUSH    BX
        PUSH    DI
        MOV     DI, OFFSET _PHRT_IBUF
        MOV     SI, DI
        TEST    AX, AX
        JNS     _PHRT_IA_POS
        MOV     BYTE PTR [DI], 2Dh
        INC     DI
        NEG     AX
_PHRT_IA_POS:
        MOV     BX, 10
        XOR     CX, CX
_PHRT_IA_LP:
        XOR     DX, DX
        DIV     BX
        ADD     DL, 30h
        PUSH    DX
        INC     CX
        TEST    AX, AX
        JNZ     _PHRT_IA_LP
_PHRT_IA_POP:
        POP     DX
        MOV     [DI], DL
        INC     DI
        LOOP    _PHRT_IA_POP
        MOV     BYTE PTR [DI], 0
        POP     DI
        POP     BX
        POP     DX
        POP     CX
        RET

_PHRT_ATOI:
        PUSH    BP
        MOV     BP, SP
        PUSH    SI
        PUSH    BX
        PUSH    CX
        MOV     SI, [BP+4]
        XOR     AX, AX
        MOV     CX, 1
        CMP     BYTE PTR [SI], 2Dh
        JNE     _PHRT_AI_LP
        MOV     CX, -1
        INC     SI
_PHRT_AI_LP:
        MOV     BL, [SI]
        CMP     BL, 30h
        JB      _PHRT_AI_DN
        CMP     BL, 39h
        JA      _PHRT_AI_DN
        IMUL    AX, AX, 10
        SUB     BL, 30h
        XOR     BH, BH
        ADD     AX, BX
        INC     SI
        JMP     _PHRT_AI_LP
_PHRT_AI_DN:
        IMUL    AX, CX
        POP     CX
        POP     BX
        POP     SI
        POP     BP
        RET

_PHRT_CONCAT:
        PUSH    SI
        PUSH    BX
        MOV     BX, SI
_PHRT_CC_END:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_CC_CPY
        INC     SI
        JMP     _PHRT_CC_END
_PHRT_CC_CPY:
        MOV     AL, [DI]
        MOV     [SI], AL
        INC     SI
        INC     DI
        TEST    AL, AL
        JNZ     _PHRT_CC_CPY
        MOV     AX, BX
        POP     BX
        POP     SI
        RET

_PHRT_STREQ:
        PUSH    SI
        PUSH    DI
        PUSH    BX
_PHRT_SE_LP:
        MOV     AL, [SI]
        MOV     BL, [DI]
        CMP     AL, BL
        JNE     _PHRT_SE_NO
        TEST    AL, AL
        JZ      _PHRT_SE_YES
        INC     SI
        INC     DI
        JMP     _PHRT_SE_LP
_PHRT_SE_YES:
        MOV     AX, 1
        JMP     _PHRT_SE_DN
_PHRT_SE_NO:
        XOR     AX, AX
_PHRT_SE_DN:
        POP     BX
        POP     DI
        POP     SI
        RET

_PHRT_POWER:
        PUSH    BX
        PUSH    CX
        MOV     BX, AX
        MOV     AX, 1
        TEST    CX, CX
        JZ      _PHRT_PW_DN
_PHRT_PW_LP:
        IMUL    AX, BX
        LOOP    _PHRT_PW_LP
_PHRT_PW_DN:
        POP     CX
        POP     BX
        RET

_PHRT_ARRAY_PUSH:
        XOR     AX, AX
        RET

_PHRT_PANIC:
        CALL    _PHRT_PRINTLN
        MOV     AX, 4C01h
        INT     21h


_TEXT   ENDS

_DATA   SEGMENT PUBLIC 'DATA'
        ASSUME  DS:_DATA
_PHK_1:
        DB      13,10,0
_PHK_2:
        DB      87,73,78,51,50,0
_PHK_3:
        DB      61,61,61,32,99,111,110,116,114,111,108,46,112,104,112,32,61,61,61,10,0
_PHK_4:
        DB      110,32,61,32,0
_PHK_5:
        DB      10,0
_PHK_8:
        DB      103,114,97,110,100,10,0
_PHK_10:
        DB      109,111,121,101,110,10,0
_PHK_11:
        DB      112,101,116,105,116,10,0
_PHK_12:
        DB      119,104,105,108,101,32,49,46,46,53,32,58,32,0
_PHK_15:
        DB      32,0
_PHK_16:
        DB      100,111,45,119,104,105,108,101,32,51,46,46,49,32,58,32,0
_PHK_20:
        DB      102,111,114,32,48,46,46,52,32,58,32,0
_PHK_25:
        DB      102,111,114,32,98,114,101,97,107,32,97,32,51,32,58,32,0
_PHK_32:
        DB      102,111,114,32,105,109,112,97,105,114,115,32,48,46,46,57,32,58,32,0
_PHK_39:
        DB      115,119,105,116,99,104,40,0
_PHK_40:
        DB      41,32,58,32,0
_PHK_44:
        DB      117,110,10,0
_PHK_47:
        DB      100,101,117,120,10,0
_PHK_50:
        DB      116,114,111,105,115,10,0
_PHK_51:
        DB      97,117,116,114,101,10,0
_PHK_52:
        DB      97,32,38,38,32,98,32,61,32,0
_PHK_54:
        DB      97,32,124,124,32,98,32,61,32,0
_PHK_56:
        DB      33,97,32,32,32,32,32,61,32,0
_PHK_57:
        DB      61,61,61,32,70,105,110,32,99,111,110,116,114,111,108,46,112,104,112,32,61,61,61,10,0
_PHRT_CRLF:
        DB      13,10,0
_PHRT_IBUF:
        DB      32,32,32,32,32,32,32,32,32,32,32,32,0
_DATA   ENDS

        END     _PHF_main
