// Generated by PHP2CS v0.1
// Source: SAMPLES/PHP/hello.php
// Target: C# 10.0

using System;
using System.Collections.Generic;

Console.Write("﻿");
Console.Write($"=== Hello, World! ===\n");
string Nom = $"DOS";
Console.Write($"Bonjour depuis ");
Console.Write(APPNAME);
Console.Write($" pour ");
Console.Write(Nom);
Console.Write($"\n");
int Annee = 2026;
Console.Write($"Annee    : " + Annee + $"\n");
Console.Write($"Version  : " + APPVER + $"\n");
Console.Write($"OS cible : " + PHPOS + $"\n");
Console.Write($"INT_MAX  : " + PHPINTMAX + $"\n");
int A = 10;
int B = 3;
Console.Write(A + $" + " + B + $" = " + A + B + $"\n");
Console.Write(A + $" - " + B + $" = " + A - B + $"\n");
Console.Write(A + $" * " + B + $" = " + A * B + $"\n");
Console.Write(A + $" / 