; Generated by PHP86 v1.0 (2026-03-05)
; Source : SAMPLES\PHP\hello.php
; Cible  : 8086 DOS (.MODEL SMALL)
; Pile   : 1024 octets

        .MODEL  SMALL
        .STACK  1024

_TEXT   SEGMENT PUBLIC 'CODE'
        ASSUME  CS:_TEXT

; Point d'entree programme PHP86
_PHF_main:
	MOV	AX, @DATA
	MOV	DS, AX
	MOV	AX, SS
	MOV	ES, AX

; -- Code PHP traduit ---

	MOV	AX, 1
	MOV	AX, 1
; echo
	MOV	AX, OFFSET _PHK_4
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $nom [BP-2]
	SUB	SP, 2
	MOV	AX, OFFSET _PHK_5
	MOV	[BP-2], AX
; echo
	MOV	AX, OFFSET _PHK_6
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_3
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_7
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-2]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $annee [BP-2]
	SUB	SP, 2
	MOV	AX, 2026
	MOV	[BP-4], AX
; echo
	MOV	AX, OFFSET _PHK_9
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-4]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_10
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, 1
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_11
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_2
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_12
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, 32767
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $a [BP-2]
	SUB	SP, 2
	MOV	AX, 10
	MOV	[BP-6], AX
; local $b [BP-2]
	SUB	SP, 2
	MOV	AX, 3
	MOV	[BP-8], AX
; echo
	MOV	AX, [BP-6]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_13
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-8]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_14
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-6]
	PUSH	AX
	MOV	AX, [BP-8]
	MOV	BX, AX
	POP	AX
	ADD	AX, BX
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-6]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_15
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-8]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_14
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-6]
	PUSH	AX
	MOV	AX, [BP-8]
	MOV	BX, AX
	POP	AX
	SUB	AX, BX
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-6]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_16
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-8]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_14
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-6]
	PUSH	AX
	MOV	AX, [BP-8]
	MOV	BX, AX
	POP	AX
	IMUL	BX
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-6]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-8]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_14
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-6]
	PUSH	AX
	MOV	AX, [BP-8]
	MOV	BX, AX
	POP	AX
	CWD
	IDIV	BX
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-6]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_18
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-8]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_14
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-6]
	PUSH	AX
	MOV	AX, [BP-8]
	MOV	BX, AX
	POP	AX
	CWD
	IDIV	BX
	MOV	AX, DX
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_19
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-6]
	PUSH	AX
	MOV	AX, [BP-8]
	MOV	BX, AX
	POP	AX
	CMP	AX, BX
	MOV	AX, 0
	SETG	AL
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_20
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-6]
	PUSH	AX
	MOV	AX, [BP-8]
	MOV	BX, AX
	POP	AX
	CMP	AX, BX
	MOV	AX, 0
	SETE	AL
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_21
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-6]
	PUSH	AX
	MOV	AX, [BP-8]
	MOV	BX, AX
	POP	AX
	CMP	AX, BX
	MOV	AX, 0
	SETNE	AL
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_22
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, 5
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_8
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_23
	MOV	SI, AX
	CALL	_PHRT_PRINT

; -- Fin de programme --
	MOV	AX, 4C00h
	INT	21h


; ============================================================
; RUNTIME PHP86 -- TODO 22
; ============================================================

_PHRT_STRLEN:
        PUSH    BP
        MOV     BP, SP
        PUSH    SI
        MOV     SI, [BP+4]
        XOR     AX, AX
_PHRT_SL_LP:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_SL_DN
        INC     SI
        INC     AX
        JMP     _PHRT_SL_LP
_PHRT_SL_DN:
        POP     SI
        POP     BP
        RET

_PHRT_PRINT:
        PUSH    AX
        PUSH    BX
        PUSH    CX
        PUSH    DX
        PUSH    SI
        MOV     DX, SI
        XOR     CX, CX
_PHRT_PR_LN:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_PR_DN
        INC     SI
        INC     CX
        JMP     _PHRT_PR_LN
_PHRT_PR_DN:
        JCXZ    _PHRT_PR_RET
        MOV     AH, 40h
        MOV     BX, 1
        INT     21h
_PHRT_PR_RET:
        POP     SI
        POP     DX
        POP     CX
        POP     BX
        POP     AX
        RET

_PHRT_NEWLINE:
        PUSH    SI
        MOV     SI, OFFSET _PHRT_CRLF
        CALL    _PHRT_PRINT
        POP     SI
        RET

_PHRT_PRINTLN:
        CALL    _PHRT_PRINT
        CALL    _PHRT_NEWLINE
        RET

_PHRT_ITOA:
        PUSH    CX
        PUSH    DX
        PUSH    BX
        PUSH    DI
        MOV     DI, OFFSET _PHRT_IBUF
        MOV     SI, DI
        TEST    AX, AX
        JNS     _PHRT_IA_POS
        MOV     BYTE PTR [DI], 2Dh
        INC     DI
        NEG     AX
_PHRT_IA_POS:
        MOV     BX, 10
        XOR     CX, CX
_PHRT_IA_LP:
        XOR     DX, DX
        DIV     BX
        ADD     DL, 30h
        PUSH    DX
        INC     CX
        TEST    AX, AX
        JNZ     _PHRT_IA_LP
_PHRT_IA_POP:
        POP     DX
        MOV     [DI], DL
        INC     DI
        LOOP    _PHRT_IA_POP
        MOV     BYTE PTR [DI], 0
        POP     DI
        POP     BX
        POP     DX
        POP     CX
        RET

_PHRT_ATOI:
        PUSH    BP
        MOV     BP, SP
        PUSH    SI
        PUSH    BX
        PUSH    CX
        MOV     SI, [BP+4]
        XOR     AX, AX
        MOV     CX, 1
        CMP     BYTE PTR [SI], 2Dh
        JNE     _PHRT_AI_LP
        MOV     CX, -1
        INC     SI
_PHRT_AI_LP:
        MOV     BL, [SI]
        CMP     BL, 30h
        JB      _PHRT_AI_DN
        CMP     BL, 39h
        JA      _PHRT_AI_DN
        IMUL    AX, AX, 10
        SUB     BL, 30h
        XOR     BH, BH
        ADD     AX, BX
        INC     SI
        JMP     _PHRT_AI_LP
_PHRT_AI_DN:
        IMUL    AX, CX
        POP     CX
        POP     BX
        POP     SI
        POP     BP
        RET

_PHRT_CONCAT:
        PUSH    SI
        PUSH    BX
        MOV     BX, SI
_PHRT_CC_END:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_CC_CPY
        INC     SI
        JMP     _PHRT_CC_END
_PHRT_CC_CPY:
        MOV     AL, [DI]
        MOV     [SI], AL
        INC     SI
        INC     DI
        TEST    AL, AL
        JNZ     _PHRT_CC_CPY
        MOV     AX, BX
        POP     BX
        POP     SI
        RET

_PHRT_STREQ:
        PUSH    SI
        PUSH    DI
        PUSH    BX
_PHRT_SE_LP:
        MOV     AL, [SI]
        MOV     BL, [DI]
        CMP     AL, BL
        JNE     _PHRT_SE_NO
        TEST    AL, AL
        JZ      _PHRT_SE_YES
        INC     SI
        INC     DI
        JMP     _PHRT_SE_LP
_PHRT_SE_YES:
        MOV     AX, 1
        JMP     _PHRT_SE_DN
_PHRT_SE_NO:
        XOR     AX, AX
_PHRT_SE_DN:
        POP     BX
        POP     DI
        POP     SI
        RET

_PHRT_POWER:
        PUSH    BX
        PUSH    CX
        MOV     BX, AX
        MOV     AX, 1
        TEST    CX, CX
        JZ      _PHRT_PW_DN
_PHRT_PW_LP:
        IMUL    AX, BX
        LOOP    _PHRT_PW_LP
_PHRT_PW_DN:
        POP     CX
        POP     BX
        RET

_PHRT_ARRAY_PUSH:
        XOR     AX, AX
        RET

_PHRT_PANIC:
        CALL    _PHRT_PRINTLN
        MOV     AX, 4C01h
        INT     21h


_TEXT   ENDS

_DATA   SEGMENT PUBLIC 'DATA'
        ASSUME  DS:_DATA
_PHK_1:
        DB      13,10,0
_PHK_2:
        DB      87,73,78,51,50,0
_PHK_3:
        DB      80,72,80,56,54,0
_PHK_4:
        DB      61,61,61,32,72,101,108,108,111,44,32,87,111,114,108,100,33,32,61,61,61,10,0
_PHK_5:
        DB      68,79,83,0
_PHK_6:
        DB      66,111,110,106,111,117,114,32,100,101,112,117,105,115,32,0
_PHK_7:
        DB      32,112,111,117,114,32,0
_PHK_8:
        DB      10,0
_PHK_9:
        DB      65,110,110,101,101,32,32,32,32,58,32,0
_PHK_10:
        DB      86,101,114,115,105,111,110,32,32,58,32,0
_PHK_11:
        DB      79,83,32,99,105,98,108,101,32,58,32,0
_PHK_12:
        DB      73,78,84,95,77,65,88,32,32,58,32,0
_PHK_13:
        DB      32,43,32,0
_PHK_14:
        DB      32,61,32,0
_PHK_15:
        DB      32,45,32,0
_PHK_16:
        DB      32,42,32,0
_PHK_17:
        DB      32,47,32,0
_PHK_18:
        DB      32,37,32,0
_PHK_19:
        DB      49,48,32,62,32,51,32,32,58,32,0
_PHK_20:
        DB      49,48,32,61,61,32,51,32,58,32,0
_PHK_21:
        DB      49,48,32,33,61,32,51,32,58,32,0
_PHK_22:
        DB      77,65,88,95,73,84,69,82,32,58,32,0
_PHK_23:
        DB      61,61,61,32,70,105,110,32,104,101,108,108,111,46,112,104,112,32,61,61,61,10,0
_PHRT_CRLF:
        DB      13,10,0
_PHRT_IBUF:
        DB      32,32,32,32,32,32,32,32,32,32,32,32,0
_DATA   ENDS

        END     _PHF_main
