; Generated by PHP86 v1.0 (2026-03-05)
; Source : SAMPLES\PHP\math.php
; Cible  : 8086 DOS (.MODEL SMALL)
; Pile   : 1024 octets

        .MODEL  SMALL
        .STACK  1024

_TEXT   SEGMENT PUBLIC 'CODE'
        ASSUME  CS:_TEXT

; Point d'entree programme PHP86
_PHF_main:
	MOV	AX, @DATA
	MOV	DS, AX
	MOV	AX, SS
	MOV	ES, AX

; -- Code PHP traduit ---

	JMP	_PHF_carre_END

; function carre
_PHF_carre:
	PUSH	BP
	MOV	BP, SP
; frame function carre (locaux alloues incrementalement)
; param $n = [BP+4]
	MOV	AX, [BP+4]
	PUSH	AX
	MOV	AX, [BP+4]
	MOV	BX, AX
	POP	AX
	IMUL	BX
	JMP	_PHL_FNRET_3
_PHL_FNRET_3:
	MOV	SP, BP
	POP	BP
	RET
_PHF_carre_END:

	JMP	_PHF_somme_END

; function somme
_PHF_somme:
	PUSH	BP
	MOV	BP, SP
; frame function somme (locaux alloues incrementalement)
; param $a = [BP+6]
; param $b = [BP+4]
	MOV	AX, [BP+6]
	PUSH	AX
	MOV	AX, [BP+4]
	MOV	BX, AX
	POP	AX
	ADD	AX, BX
	JMP	_PHL_FNRET_4
_PHL_FNRET_4:
	MOV	SP, BP
	POP	BP
	RET
_PHF_somme_END:

	JMP	_PHF_factorielle_END

; function factorielle
_PHF_factorielle:
	PUSH	BP
	MOV	BP, SP
; frame function factorielle (locaux alloues incrementalement)
; param $n = [BP+4]
; local $r [BP-2]
	SUB	SP, 2
	MOV	AX, 1
	MOV	[BP-2], AX
; local $i [BP-2]
	SUB	SP, 2
	MOV	AX, 1
	MOV	[BP-4], AX
_PHL_WHTOP_6:
	MOV	AX, [BP-4]
	PUSH	AX
	MOV	AX, [BP+4]
	MOV	BX, AX
	POP	AX
	CMP	AX, BX
	MOV	AX, 0
	SETLE	AL
	TEST	AX, AX
	JZ	_PHL_WHEND_7
	MOV	AX, [BP-2]
	PUSH	AX
	MOV	AX, [BP-4]
	MOV	BX, AX
	POP	AX
	IMUL	BX
	MOV	[BP-2], AX
	MOV	AX, [BP-4]
	ADD	AX, 1
	MOV	[BP-4], AX
	JMP	_PHL_WHTOP_6
_PHL_WHEND_7:
	MOV	AX, [BP-2]
	JMP	_PHL_FNRET_5
_PHL_FNRET_5:
	MOV	SP, BP
	POP	BP
	RET
_PHF_factorielle_END:

	JMP	_PHF_pgcd_END

; function pgcd
_PHF_pgcd:
	PUSH	BP
	MOV	BP, SP
; frame function pgcd (locaux alloues incrementalement)
; param $a = [BP+6]
; param $b = [BP+4]
_PHL_WHTOP_9:
	MOV	AX, [BP+4]
	CMP	AX, 0
	MOV	AX, 0
	SETNE	AL
	TEST	AX, AX
	JZ	_PHL_WHEND_10
; local $t [BP-2]
	SUB	SP, 2
	MOV	AX, [BP+4]
	MOV	[BP-2], AX
	MOV	AX, [BP+6]
	PUSH	AX
	MOV	AX, [BP+4]
	MOV	BX, AX
	POP	AX
	CWD
	IDIV	BX
	MOV	AX, DX
	MOV	[BP+4], AX
	MOV	AX, [BP-2]
	MOV	[BP+6], AX
	JMP	_PHL_WHTOP_9
_PHL_WHEND_10:
	MOV	AX, [BP+6]
	JMP	_PHL_FNRET_8
_PHL_FNRET_8:
	MOV	SP, BP
	POP	BP
	RET
_PHF_pgcd_END:

	JMP	_PHF_mon_abs_END

; function mon_abs
_PHF_mon_abs:
	PUSH	BP
	MOV	BP, SP
; frame function mon_abs (locaux alloues incrementalement)
; param $n = [BP+4]
	MOV	AX, [BP+4]
	CMP	AX, 0
	MOV	AX, 0
	SETL	AL
	TEST	AX, AX
	JZ	_PHL_ELSE_13
	MOV	AX, 0
	PUSH	AX
	MOV	AX, [BP+4]
	MOV	BX, AX
	POP	AX
	SUB	AX, BX
	JMP	_PHL_FNRET_11
_PHL_ELSE_13:
_PHL_ENDIF_12:
	MOV	AX, [BP+4]
	JMP	_PHL_FNRET_11
_PHL_FNRET_11:
	MOV	SP, BP
	POP	BP
	RET
_PHF_mon_abs_END:

; echo
	MOV	AX, OFFSET _PHK_14
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $x [BP-2]
	SUB	SP, 2
	MOV	AX, 6
	MOV	[BP-2], AX
; local $y [BP-2]
	SUB	SP, 2
	MOV	AX, 4
	MOV	[BP-4], AX
; echo
	MOV	AX, OFFSET _PHK_15
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-2]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_16
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
	PUSH	AX
	CALL	_PHF_carre
	ADD	SP, 2
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_18
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-2]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_19
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-4]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_20
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
	PUSH	AX
	MOV	AX, [BP-4]
	PUSH	AX
	CALL	_PHF_somme
	ADD	SP, 4
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_21
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, 5
	PUSH	AX
	CALL	_PHF_factorielle
	ADD	SP, 2
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_22
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, 7
	PUSH	AX
	CALL	_PHF_factorielle
	ADD	SP, 2
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_23
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, 48
	PUSH	AX
	MOV	AX, 18
	PUSH	AX
	CALL	_PHF_pgcd
	ADD	SP, 4
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_24
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, -42
	PUSH	AX
	CALL	_PHF_mon_abs
	ADD	SP, 2
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_25
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, -99
	CWD
	XOR	AX, DX
	SUB	AX, DX
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_26
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-2]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_19
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-4]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_27
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
	PUSH	AX
	MOV	AX, [BP-4]
	POP	BX
	CMP	AX, BX
	JGE	_PHL__PHL_MAX_28
	MOV	AX, BX
_PHL__PHL_MAX_28:
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_29
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-2]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_19
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-4]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_27
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-2]
	PUSH	AX
	MOV	AX, [BP-4]
	POP	BX
	CMP	AX, BX
	JLE	_PHL__PHL_MIN_30
	MOV	AX, BX
_PHL__PHL_MIN_30:
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; local $base [BP-2]
	SUB	SP, 2
	MOV	AX, 2
	MOV	[BP-6], AX
; local $exp [BP-2]
	SUB	SP, 2
	MOV	AX, 8
	MOV	[BP-8], AX
; echo
	MOV	AX, [BP-6]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_31
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, [BP-8]
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_32
	MOV	SI, AX
	CALL	_PHRT_PRINT
	MOV	AX, [BP-6]
	PUSH	AX
	MOV	AX, [BP-8]
	MOV	BX, AX
	POP	AX
	XCHG	AX, BX
	MOV	CX, BX
	MOV	AX, AX
	CALL	_PHRT_POWER
; echo
	CALL	_PHRT_ITOA
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_17
	MOV	SI, AX
	CALL	_PHRT_PRINT
; echo
	MOV	AX, OFFSET _PHK_33
	MOV	SI, AX
	CALL	_PHRT_PRINT

; -- Fin de programme --
	MOV	AX, 4C00h
	INT	21h


; ============================================================
; RUNTIME PHP86 -- TODO 22
; ============================================================

_PHRT_STRLEN:
        PUSH    BP
        MOV     BP, SP
        PUSH    SI
        MOV     SI, [BP+4]
        XOR     AX, AX
_PHRT_SL_LP:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_SL_DN
        INC     SI
        INC     AX
        JMP     _PHRT_SL_LP
_PHRT_SL_DN:
        POP     SI
        POP     BP
        RET

_PHRT_PRINT:
        PUSH    AX
        PUSH    BX
        PUSH    CX
        PUSH    DX
        PUSH    SI
        MOV     DX, SI
        XOR     CX, CX
_PHRT_PR_LN:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_PR_DN
        INC     SI
        INC     CX
        JMP     _PHRT_PR_LN
_PHRT_PR_DN:
        JCXZ    _PHRT_PR_RET
        MOV     AH, 40h
        MOV     BX, 1
        INT     21h
_PHRT_PR_RET:
        POP     SI
        POP     DX
        POP     CX
        POP     BX
        POP     AX
        RET

_PHRT_NEWLINE:
        PUSH    SI
        MOV     SI, OFFSET _PHRT_CRLF
        CALL    _PHRT_PRINT
        POP     SI
        RET

_PHRT_PRINTLN:
        CALL    _PHRT_PRINT
        CALL    _PHRT_NEWLINE
        RET

_PHRT_ITOA:
        PUSH    CX
        PUSH    DX
        PUSH    BX
        PUSH    DI
        MOV     DI, OFFSET _PHRT_IBUF
        MOV     SI, DI
        TEST    AX, AX
        JNS     _PHRT_IA_POS
        MOV     BYTE PTR [DI], 2Dh
        INC     DI
        NEG     AX
_PHRT_IA_POS:
        MOV     BX, 10
        XOR     CX, CX
_PHRT_IA_LP:
        XOR     DX, DX
        DIV     BX
        ADD     DL, 30h
        PUSH    DX
        INC     CX
        TEST    AX, AX
        JNZ     _PHRT_IA_LP
_PHRT_IA_POP:
        POP     DX
        MOV     [DI], DL
        INC     DI
        LOOP    _PHRT_IA_POP
        MOV     BYTE PTR [DI], 0
        POP     DI
        POP     BX
        POP     DX
        POP     CX
        RET

_PHRT_ATOI:
        PUSH    BP
        MOV     BP, SP
        PUSH    SI
        PUSH    BX
        PUSH    CX
        MOV     SI, [BP+4]
        XOR     AX, AX
        MOV     CX, 1
        CMP     BYTE PTR [SI], 2Dh
        JNE     _PHRT_AI_LP
        MOV     CX, -1
        INC     SI
_PHRT_AI_LP:
        MOV     BL, [SI]
        CMP     BL, 30h
        JB      _PHRT_AI_DN
        CMP     BL, 39h
        JA      _PHRT_AI_DN
        IMUL    AX, AX, 10
        SUB     BL, 30h
        XOR     BH, BH
        ADD     AX, BX
        INC     SI
        JMP     _PHRT_AI_LP
_PHRT_AI_DN:
        IMUL    AX, CX
        POP     CX
        POP     BX
        POP     SI
        POP     BP
        RET

_PHRT_CONCAT:
        PUSH    SI
        PUSH    BX
        MOV     BX, SI
_PHRT_CC_END:
        CMP     BYTE PTR [SI], 0
        JE      _PHRT_CC_CPY
        INC     SI
        JMP     _PHRT_CC_END
_PHRT_CC_CPY:
        MOV     AL, [DI]
        MOV     [SI], AL
        INC     SI
        INC     DI
        TEST    AL, AL
        JNZ     _PHRT_CC_CPY
        MOV     AX, BX
        POP     BX
        POP     SI
        RET

_PHRT_STREQ:
        PUSH    SI
        PUSH    DI
        PUSH    BX
_PHRT_SE_LP:
        MOV     AL, [SI]
        MOV     BL, [DI]
        CMP     AL, BL
        JNE     _PHRT_SE_NO
        TEST    AL, AL
        JZ      _PHRT_SE_YES
        INC     SI
        INC     DI
        JMP     _PHRT_SE_LP
_PHRT_SE_YES:
        MOV     AX, 1
        JMP     _PHRT_SE_DN
_PHRT_SE_NO:
        XOR     AX, AX
_PHRT_SE_DN:
        POP     BX
        POP     DI
        POP     SI
        RET

_PHRT_POWER:
        PUSH    BX
        PUSH    CX
        MOV     BX, AX
        MOV     AX, 1
        TEST    CX, CX
        JZ      _PHRT_PW_DN
_PHRT_PW_LP:
        IMUL    AX, BX
        LOOP    _PHRT_PW_LP
_PHRT_PW_DN:
        POP     CX
        POP     BX
        RET

_PHRT_ARRAY_PUSH:
        XOR     AX, AX
        RET

_PHRT_PANIC:
        CALL    _PHRT_PRINTLN
        MOV     AX, 4C01h
        INT     21h


_TEXT   ENDS

_DATA   SEGMENT PUBLIC 'DATA'
        ASSUME  DS:_DATA
_PHK_1:
        DB      13,10,0
_PHK_2:
        DB      87,73,78,51,50,0
_PHK_14:
        DB      61,61,61,32,109,97,116,104,46,112,104,112,32,61,61,61,10,0
_PHK_15:
        DB      99,97,114,114,101,40,0
_PHK_16:
        DB      41,32,32,32,32,32,32,32,61,32,0
_PHK_17:
        DB      10,0
_PHK_18:
        DB      115,111,109,109,101,40,0
_PHK_19:
        DB      44,32,0
_PHK_20:
        DB      41,32,61,32,0
_PHK_21:
        DB      102,97,99,116,111,114,105,101,108,108,101,40,53,41,32,32,61,32,0
_PHK_22:
        DB      102,97,99,116,111,114,105,101,108,108,101,40,55,41,32,32,61,32,0
_PHK_23:
        DB      112,103,99,100,40,52,56,44,32,49,56,41,32,32,32,32,61,32,0
_PHK_24:
        DB      109,111,110,95,97,98,115,40,45,52,50,41,32,32,32,32,61,32,0
_PHK_25:
        DB      97,98,115,40,45,57,57,41,32,32,32,32,32,32,32,32,61,32,0
_PHK_26:
        DB      109,97,120,40,0
_PHK_27:
        DB      41,32,32,32,61,32,0
_PHK_29:
        DB      109,105,110,40,0
_PHK_31:
        DB      32,42,42,32,0
_PHK_32:
        DB      32,61,32,0
_PHK_33:
        DB      61,61,61,32,70,105,110,32,109,97,116,104,46,112,104,112,32,61,61,61,10,0
_PHRT_CRLF:
        DB      13,10,0
_PHRT_IBUF:
        DB      32,32,32,32,32,32,32,32,32,32,32,32,0
_DATA   ENDS

        END     _PHF_main
