/* Generated by TP2JS 1.0 - 2026-03-10 */
"use strict";

// CRT color helpers
var TextAttr = 7, WindMin = 0, WindMax = 0x184F, LastMode = 3;
var DirectVideo = true, CheckBreak = true, CheckEOF = false, CheckSnow = true;
function _TPR_CrtFg(c) {
  var m = [30,34,32,36,31,35,33,37,90,94,92,96,91,95,93,97];
  return (c >= 0 && c <= 15) ? String(m[c]) : "37";
}
function _TPR_CrtBg(c) {
  var m = [40,44,42,46,41,45,43,47];
  return (c >= 0 && c <= 7) ? String(m[c]) : "40";
}

// DOS unit helpers
var DosError = 0, DosExitCode = 0;
function _TPR_PackTime(dt) {
  return ((dt.Year - 1980) << 25) | (dt.Month << 21) | (dt.Day << 16) |
         (dt.Hour << 11) | (dt.Min << 5) | (dt.Sec >> 1);
}
function _TPR_UnpackTime(t, dt) {
  dt.Year = ((t >> 25) & 0x7F) + 1980;
  dt.Month = (t >> 21) & 0x0F;
  dt.Day = (t >> 16) & 0x1F;
  dt.Hour = (t >> 11) & 0x1F;
  dt.Min = (t >> 5) & 0x3F;
  dt.Sec = (t & 0x1F) << 1;
}
function _TPR_FSplit(path, dirRef, nameRef, extRef) {
  var i = path.length - 1;
  while (i >= 0 && path[i] !== "/" && path[i] !== "\\") i--;
  var d = (i >= 0) ? path.substring(0, i + 1) : "";
  var f = path.substring(i + 1);
  var j = f.lastIndexOf(".");
  var n = (j >= 0) ? f.substring(0, j) : f;
  var e = (j >= 0) ? f.substring(j) : "";
  return { dir: d, name: n, ext: e };
}

// Program test_crt

// uses
//   Crt

var i = 0;
var ch = "";

// Corps principal
function _main() {
  process.stdout.write("\x1b[2J\x1b[H");
  process.stdout.write("\x1b[" + _TPR_CrtFg(14) + "m");
  console.log("=== Test CRT Unit ===");
  process.stdout.write("\x1b[0m");
  for (var i = 0; i <= 15; i++) {
    process.stdout.write("\x1b[" + _TPR_CrtFg(i) + "m");
    process.stdout.write(String("Color " + (i) + (" ")));
  }
  process.stdout.write("\x1b[0m");
  console.log("");
  for (var i = 0; i <= 7; i++) {
    process.stdout.write("\x1b[" + _TPR_CrtBg(i) + "m");
    process.stdout.write(String(" Bg" + (i) + (" ")));
  }
  process.stdout.write("\x1b[0m");
  console.log("");
  process.stdout.write("\x1b[" + 5 + ";" + 10 + "H");
  console.log("Position (10,5)");
  process.stdout.write("\x1b[1m");
  console.log("HighVideo");
  process.stdout.write("\x1b[2m");
  console.log("LowVideo");
  process.stdout.write("\x1b[0m");
  console.log("NormVideo");
  process.stdout.write("\x1b[L");
  process.stdout.write("\x1b[M");
  process.stdout.write("\x1b[K");
  process.stdout.write("\x1b[" + _TPR_CrtFg(4) + "m");
  console.log("Rouge");
  process.stdout.write("\x1b[" + _TPR_CrtFg(2) + "m");
  console.log("Vert");
  process.stdout.write("\x1b[" + _TPR_CrtFg(11) + "m");
  console.log("Cyan clair");
  process.stdout.write("\x1b[" + _TPR_CrtBg(1) + "m");
  console.log("Fond bleu");
  process.stdout.write("\x1b[0m");
  console.log("CO80 = " + (3));
  console.log("BW80 = " + (2));
  /* Delay(100) */;
  /* Sound(440) */;
  /* NoSound */;
  /* Window(1, 1, 80, 25) */;
  /* TextMode(3) */;
  console.log("=== Fin test CRT ===");
}

// Programme principal
_main();
