/* Generated by TP2JS 1.0 - 2026-03-10 */
"use strict";

// CRT color helpers
var TextAttr = 7, WindMin = 0, WindMax = 0x184F, LastMode = 3;
var DirectVideo = true, CheckBreak = true, CheckEOF = false, CheckSnow = true;
function _TPR_CrtFg(c) {
  var m = [30,34,32,36,31,35,33,37,90,94,92,96,91,95,93,97];
  return (c >= 0 && c <= 15) ? String(m[c]) : "37";
}
function _TPR_CrtBg(c) {
  var m = [40,44,42,46,41,45,43,47];
  return (c >= 0 && c <= 7) ? String(m[c]) : "40";
}

// DOS unit helpers
var DosError = 0, DosExitCode = 0;
function _TPR_PackTime(dt) {
  return ((dt.Year - 1980) << 25) | (dt.Month << 21) | (dt.Day << 16) |
         (dt.Hour << 11) | (dt.Min << 5) | (dt.Sec >> 1);
}
function _TPR_UnpackTime(t, dt) {
  dt.Year = ((t >> 25) & 0x7F) + 1980;
  dt.Month = (t >> 21) & 0x0F;
  dt.Day = (t >> 16) & 0x1F;
  dt.Hour = (t >> 11) & 0x1F;
  dt.Min = (t >> 5) & 0x3F;
  dt.Sec = (t & 0x1F) << 1;
}
function _TPR_FSplit(path, dirRef, nameRef, extRef) {
  var i = path.length - 1;
  while (i >= 0 && path[i] !== "/" && path[i] !== "\\") i--;
  var d = (i >= 0) ? path.substring(0, i + 1) : "";
  var f = path.substring(i + 1);
  var j = f.lastIndexOf(".");
  var n = (j >= 0) ? f.substring(0, j) : f;
  var e = (j >= 0) ? f.substring(j) : "";
  return { dir: d, name: n, ext: e };
}

// Program TestFunction

function Square(x) {
  var Result = null;
  var result = 0;
  Result = x * x;
  return Result;
}

function Add5(n) {
  var Result = null;
  Result = n + 5;
  return Result;
}

var a = 0;
var b = 0;

// Corps principal
function _main() {
  a = 10;
  b = Square(a);
  console.log("Square de " + (a) + (" = ") + (b));
  a = 7;
  b = Add5(a);
  console.log("Add5 de " + (a) + (" = ") + (b));
}

// Programme principal
_main();
