/* Generated by TP2JS 1.0 - 2026-03-10 */
"use strict";

// CRT color helpers
var TextAttr = 7, WindMin = 0, WindMax = 0x184F, LastMode = 3;
var DirectVideo = true, CheckBreak = true, CheckEOF = false, CheckSnow = true;
function _TPR_CrtFg(c) {
  var m = [30,34,32,36,31,35,33,37,90,94,92,96,91,95,93,97];
  return (c >= 0 && c <= 15) ? String(m[c]) : "37";
}
function _TPR_CrtBg(c) {
  var m = [40,44,42,46,41,45,43,47];
  return (c >= 0 && c <= 7) ? String(m[c]) : "40";
}

// DOS unit helpers
var DosError = 0, DosExitCode = 0;
function _TPR_PackTime(dt) {
  return ((dt.Year - 1980) << 25) | (dt.Month << 21) | (dt.Day << 16) |
         (dt.Hour << 11) | (dt.Min << 5) | (dt.Sec >> 1);
}
function _TPR_UnpackTime(t, dt) {
  dt.Year = ((t >> 25) & 0x7F) + 1980;
  dt.Month = (t >> 21) & 0x0F;
  dt.Day = (t >> 16) & 0x1F;
  dt.Hour = (t >> 11) & 0x1F;
  dt.Min = (t >> 5) & 0x3F;
  dt.Sec = (t & 0x1F) << 1;
}
function _TPR_FSplit(path, dirRef, nameRef, extRef) {
  var i = path.length - 1;
  while (i >= 0 && path[i] !== "/" && path[i] !== "\\") i--;
  var d = (i >= 0) ? path.substring(0, i + 1) : "";
  var f = path.substring(i + 1);
  var j = f.lastIndexOf(".");
  var n = (j >= 0) ? f.substring(0, j) : f;
  var e = (j >= 0) ? f.substring(j) : "";
  return { dir: d, name: n, ext: e };
}

// Program test_dos

// uses
//   Dos

var Y = 0;
var M = 0;
var D = 0;
var DOW = 0;
var H = 0;
var Mi = 0;
var S = 0;
var S100 = 0;
var Env = "";
var EC = 0;

// Corps principal
function _main() {
  console.log("=== Test DOS Unit ===");
  console.log("ReadOnly = " + (1));
  console.log("Hidden = " + (2));
  console.log("SysFile = " + (4));
  console.log("VolumeID = " + (8));
  console.log("Directory = " + (16));
  console.log("Archive = " + (32));
  console.log("AnyFile = " + (63));
  (function() { var _d = new Date(); Y = _d.getFullYear(); M = _d.getMonth() + 1; D = _d.getDate(); DOW = _d.getDay(); })();
  console.log("Year: " + (Y));
  console.log("Month: " + (M));
  console.log("Day: " + (D));
  console.log("DayOfWeek: " + (DOW));
  (function() { var _d = new Date(); H = _d.getHours(); Mi = _d.getMinutes(); S = _d.getSeconds(); S100 = Math.floor(_d.getMilliseconds() / 10); })();
  console.log("Hour: " + (H));
  console.log("Min: " + (Mi));
  console.log("Sec: " + (S));
  Env = (typeof process !== "undefined" ? (process.env["PATH"] || "") : "");
  console.log("PATH length: " + (Env.length));
  console.log("EnvCount: " + ((typeof process !== "undefined" ? Object.keys(process.env).length : 0)));
  console.log("DosVersion: " + (0x0007 /* DosVersion stub: 7.0 */));
  EC = DosExitCode;
  console.log("DosExitCode: " + (EC));
  /* SwapVectors: not relevant in JS */;
  0 /* DiskFree stub */;
  0 /* DiskSize stub */;
  console.log("=== Fin test DOS ===");
}

// Programme principal
_main();
