; Generated by RAKU86 v1.0 - 2026-03-06
; Source : SAMPLES/RAKU/test_symbols.raku

        .MODEL  SMALL
        .STACK  1024

_TEXT   SEGMENT WORD PUBLIC 'CODE'
        ASSUME  CS:_TEXT, DS:_DATA

_RKS_MAIN PROC NEAR
        MOV  AX, @DATA
        MOV  DS, AX
; Init heap pointer
        MOV  WORD PTR [_RK_HEAPTOP], OFFSET _RK_HEAP

        SUB  SP, 2
        MOV  WORD PTR [BP-2], 0
; my $x [BP-2]
        MOV  AX, 42
        MOV  [BP-2], AX
        SUB  SP, 2
        MOV  WORD PTR [BP-4], 0
; my $y [BP-4]
        MOV  AX, 10
        MOV  [BP-4], AX
        SUB  SP, 2
        MOV  WORD PTR [BP-6], 0
; my $name [BP-6]
        MOV  AX, OFFSET _RKK_1
        MOV  [BP-6], AX
; our $count -> _RKV_count
        MOV  AX, 0
        MOV  [_RKV_count], AX
        SUB  SP, 2
        MOV  WORD PTR [BP-8], 0
; my $pi [BP-8]
        MOV  AX, 3
        MOV  [BP-8], AX
        SUB  SP, 2
        MOV  WORD PTR [BP-10], 0
; my $scalar [BP-10]
        MOV  AX, 1
        MOV  [BP-10], AX
        SUB  SP, 2
        MOV  WORD PTR [BP-12], 0
; my @array [BP-12]
        SUB  SP, 2
        MOV  WORD PTR [BP-14], 0
; my %hash [BP-14]
        SUB  SP, 2
        MOV  WORD PTR [BP-16], 0
; my $z [BP-16]
        MOV  AX, [BP-2]
        MOV  AX, [BP-4]
        PUSH  AX
        POP  BX
        ADD  AX, BX
        MOV  [BP-16], AX
        MOV  AX, 5
        PUSH  AX
        MOV  AX, [BP-2]
        MOV  BX, AX
        POP  AX
        ADD  BX, AX
        MOV  AX, BX
        MOV  [BP-2], AX

; Fin du script Raku - sortie implicite code 0
        MOV  AX, 4C00h
        INT  21h
_RKS_MAIN ENDP


; === Runtime RAKU86 ===

; --- _RKRT_CONCAT : append ASCIIZ SI a DI ---
_RKRT_CONCAT PROC NEAR
        PUSH  SI
        PUSH  BX
        MOV   BX, DI
_RKRT_CC_FEND:
        CMP   BYTE PTR [DI], 0
        JE    _RKRT_CC_CPY
        INC   DI
        JMP   _RKRT_CC_FEND
_RKRT_CC_CPY:
        MOV   AL, [SI]
        MOV   [DI], AL
        INC   DI
        INC   SI
        TEST  AL, AL
        JNZ   _RKRT_CC_CPY
        MOV   AX, BX
        POP   BX
        POP   SI
        RET
_RKRT_CONCAT ENDP

; --- _RKRT_STRREPEAT : SI=str, CX=count -> AX=TMPBUF ---
_RKRT_STRREPEAT PROC NEAR
        PUSH  BX
        PUSH  DX
        MOV   BX, SI
        MOV   BYTE PTR [_RK_TMPBUF], 0
        MOV   DI, OFFSET _RK_TMPBUF
        TEST  CX, CX
        JLE   _RKRT_SR_DONE
_RKRT_SR_LOOP:
        MOV   SI, BX
        CALL  _RKRT_CONCAT
        DEC   CX
        JNZ   _RKRT_SR_LOOP
_RKRT_SR_DONE:
        MOV   AX, OFFSET _RK_TMPBUF
        POP   DX
        POP   BX
        RET
_RKRT_STRREPEAT ENDP

; --- _RKRT_STRCMP : SI=str1, DI=str2 -> AX=-1/0/+1 ---
_RKRT_STRCMP PROC NEAR
        PUSH  BX
_RKRT_SC_LOOP:
        MOV   AL, [SI]
        MOV   BL, [DI]
        CMP   AL, BL
        JB    _RKRT_SC_LT
        JA    _RKRT_SC_GT
        TEST  AL, AL
        JZ    _RKRT_SC_EQ
        INC   SI
        INC   DI
        JMP   _RKRT_SC_LOOP
_RKRT_SC_LT:
        MOV   AX, 0FFFFh
        JMP   _RKRT_SC_END
_RKRT_SC_GT:
        MOV   AX, 1
        JMP   _RKRT_SC_END
_RKRT_SC_EQ:
        XOR   AX, AX
_RKRT_SC_END:
        POP   BX
        RET
_RKRT_STRCMP ENDP

; --- _RKRT_POWER : AX=base, CX=exp -> AX=result ---
_RKRT_POWER PROC NEAR
        PUSH  BX
        PUSH  DX
        MOV   BX, AX
        MOV   AX, 1
        TEST  CX, CX
        JLE   _RKRT_PW_DONE
_RKRT_PW_LOOP:
        IMUL  BX
        DEC   CX
        JNZ   _RKRT_PW_LOOP
_RKRT_PW_DONE:
        POP   DX
        POP   BX
        RET
_RKRT_POWER ENDP


; === Runtime ENTREES/SORTIES (TODO 12) ===

; --- _RKRT_STRLEN : SI=str ASCIIZ -> CX=longueur ---
_RKRT_STRLEN PROC NEAR
        PUSH  SI
        XOR   CX, CX
_RKRT_SL_LP:
        CMP   BYTE PTR [SI], 0
        JE    _RKRT_SL_DN
        INC   SI
        INC   CX
        JMP   _RKRT_SL_LP
_RKRT_SL_DN:
        POP   SI
        RET
_RKRT_STRLEN ENDP

; --- _RKRT_PRINTSTR : SI=str ASCIIZ -> stdout ---
_RKRT_PRINTSTR PROC NEAR
        PUSH  AX
        PUSH  BX
        PUSH  CX
        PUSH  DX
        CALL  _RKRT_STRLEN
        MOV   DX, SI
        MOV   BX, 1
        MOV   AH, 40h
        INT   21h
        POP   DX
        POP   CX
        POP   BX
        POP   AX
        RET
_RKRT_PRINTSTR ENDP

; --- _RKRT_PRINTINT : AX=int16 -> stdout decimal ---
_RKRT_PRINTINT PROC NEAR
        PUSH  AX
        PUSH  BX
        PUSH  CX
        PUSH  DX
        PUSH  SI
        PUSH  DI
        LEA   DI, _RK_NUMBUF
        MOV   BX, AX
        TEST  AX, AX
        JNS   _RKRT_PI_POS
        MOV   BYTE PTR [DI], 2Dh
        INC   DI
        NEG   BX
_RKRT_PI_POS:
        MOV   AX, BX
        XOR   CX, CX
        MOV   BX, 10
_RKRT_PI_DLP:
        XOR   DX, DX
        DIV   BX
        ADD   DL, 30h
        PUSH  DX
        INC   CX
        TEST  AX, AX
        JNZ   _RKRT_PI_DLP
_RKRT_PI_SLP:
        POP   AX
        MOV   [DI], AL
        INC   DI
        DEC   CX
        JNZ   _RKRT_PI_SLP
        MOV   BYTE PTR [DI], 0
        LEA   SI, _RK_NUMBUF
        CALL  _RKRT_PRINTSTR
        POP   DI
        POP   SI
        POP   DX
        POP   CX
        POP   BX
        POP   AX
        RET
_RKRT_PRINTINT ENDP

; --- _RKRT_NEWLINE : ecrire CR+LF sur stdout ---
_RKRT_NEWLINE PROC NEAR
        PUSH  SI
        LEA   SI, _RK_CRLF
        CALL  _RKRT_PRINTSTR
        POP   SI
        RET
_RKRT_NEWLINE ENDP

; --- _RKRT_GETLINE : lire ligne STDIN -> AX=ptr ---
_RKRT_GETLINE PROC NEAR
        PUSH  BX
        PUSH  CX
        PUSH  DX
        MOV   BYTE PTR [_RK_IOBUF], 126
        MOV   BYTE PTR [_RK_IOBUF+1], 0
        LEA   DX, _RK_IOBUF
        MOV   AH, 0Ah
        INT   21h
        LEA   BX, _RK_IOBUF
        XOR   CH, CH
        MOV   CL, [BX+1]
        ADD   BX, 2
        ADD   BX, CX
        MOV   BYTE PTR [BX], 0
        MOV   AX, OFFSET _RK_IOBUF
        ADD   AX, 2
        POP   DX
        POP   CX
        POP   BX
        RET
_RKRT_GETLINE ENDP


; === Runtime TABLEAUX (TODO 15) ===

; --- _RKRT_ARRPUSH : BX=arr, CX=val -> push ---
_RKRT_ARRPUSH PROC NEAR
        PUSH  SI
        MOV   SI, [BX]
        INC   WORD PTR [BX]
        SHL   SI, 1
        ADD   SI, 2
        ADD   SI, BX
        MOV   [SI], CX
        POP   SI
        RET
_RKRT_ARRPUSH ENDP

; --- _RKRT_ARRPOP : BX=arr -> AX=last ---
_RKRT_ARRPOP PROC NEAR
        PUSH  SI
        MOV   SI, [BX]
        TEST  SI, SI
        JZ    _RKRT_AP_Z
        DEC   WORD PTR [BX]
        SHL   SI, 1
        MOV   AX, [BX+SI]
        POP   SI
        RET
_RKRT_AP_Z:
        XOR   AX, AX
        POP   SI
        RET
_RKRT_ARRPOP ENDP

; --- _RKRT_ARRSHIFT : BX=arr -> AX=first ---
_RKRT_ARRSHIFT PROC NEAR
        PUSH  SI
        PUSH  DI
        PUSH  CX
        MOV   CX, [BX]
        TEST  CX, CX
        JZ    _RKRT_AS_Z
        MOV   AX, [BX+2]
        DEC   WORD PTR [BX]
        DEC   CX
        LEA   DI, [BX+2]
        LEA   SI, [BX+4]
        REP   MOVSW
        POP   CX
        POP   DI
        POP   SI
        RET
_RKRT_AS_Z:
        XOR   AX, AX
        POP   CX
        POP   DI
        POP   SI
        RET
_RKRT_ARRSHIFT ENDP

; --- _RKRT_ARRUNSHIFT : BX=arr, CX=val -> unshift ---
_RKRT_ARRUNSHIFT PROC NEAR
        PUSH  SI
        PUSH  DI
        PUSH  CX
        MOV   AX, [BX]
        INC   WORD PTR [BX]
        TEST  AX, AX
        JZ    _RKRT_AU_INS
        MOV   CX, AX
        MOV   SI, AX
        SHL   SI, 1
        LEA   SI, [BX+SI]
        LEA   DI, [SI+2]
        STD
        REP   MOVSW
        CLD
_RKRT_AU_INS:
        POP   CX
        MOV   [BX+2], CX
        POP   DI
        POP   SI
        RET
_RKRT_ARRUNSHIFT ENDP

; --- _RKRT_ARRREVERSE : BX=arr -> reverse ---
_RKRT_ARRREVERSE PROC NEAR
        PUSH  SI
        PUSH  DI
        MOV   CX, [BX]
        CMP   CX, 2
        JB    _RKRT_ARV_DN
        LEA   SI, [BX+2]
        MOV   DI, CX
        SHL   DI, 1
        LEA   DI, [BX+DI]
        SUB   DI, 2
_RKRT_ARV_LP:
        CMP   SI, DI
        JAE   _RKRT_ARV_DN
        MOV   AX, [SI]
        MOV   CX, [DI]
        MOV   [SI], CX
        MOV   [DI], AX
        ADD   SI, 2
        SUB   DI, 2
        JMP   _RKRT_ARV_LP
_RKRT_ARV_DN:
        POP   DI
        POP   SI
        RET
_RKRT_ARRREVERSE ENDP

; --- _RKRT_ARRSORT : BX=arr -> insertion sort ---
_RKRT_ARRSORT PROC NEAR
        PUSH  SI
        PUSH  DI
        PUSH  CX
        PUSH  DX
        MOV   CX, [BX]
        CMP   CX, 2
        JB    _RKRT_AST_DN
        MOV   SI, 1
_RKRT_AST_OT:
        CMP   SI, CX
        JAE   _RKRT_AST_DN
        MOV   DI, SI
        SHL   DI, 1
        MOV   DX, [BX+DI+2]
        MOV   DI, SI
_RKRT_AST_IN:
        TEST  DI, DI
        JZ    _RKRT_AST_PL
        MOV   AX, DI
        DEC   AX
        SHL   AX, 1
        ADD   AX, 2
        PUSH  BX
        ADD   BX, AX
        MOV   AX, [BX]
        POP   BX
        CMP   AX, DX
        JLE   _RKRT_AST_PL
        PUSH  DI
        SHL   DI, 1
        MOV   [BX+DI+2], AX
        POP   DI
        DEC   DI
        JMP   _RKRT_AST_IN
_RKRT_AST_PL:
        PUSH  DI
        SHL   DI, 1
        MOV   [BX+DI+2], DX
        POP   DI
        INC   SI
        JMP   _RKRT_AST_OT
_RKRT_AST_DN:
        POP   DX
        POP   CX
        POP   DI
        POP   SI
        RET
_RKRT_ARRSORT ENDP

; --- _RKRT_ARRJOIN : BX=arr, SI=sep -> AX=str ---
_RKRT_ARRJOIN PROC NEAR
        PUSH  DI
        PUSH  CX
        PUSH  DX
        PUSH  BX
        MOV   DI, OFFSET _RK_STRBUF
        MOV   BYTE PTR [DI], 0
        MOV   CX, [BX]
        TEST  CX, CX
        JZ    _RKRT_AJ_DN
        ADD   BX, 2
        XOR   DX, DX
_RKRT_AJ_LP:
        TEST  DX, DX
        JZ    _RKRT_AJ_NOS
        PUSH  SI
        PUSH  CX
        PUSH  BX
        CALL  _RKRT_CONCAT
        POP   BX
        POP   CX
        POP   SI
_RKRT_AJ_NOS:
        PUSH  SI
        PUSH  CX
        PUSH  BX
        PUSH  DX
        MOV   AX, [BX]
        CALL  _RKRT_ITOA
        MOV   SI, AX
        CALL  _RKRT_CONCAT
        POP   DX
        POP   BX
        POP   CX
        POP   SI
        ADD   BX, 2
        INC   DX
        CMP   DX, CX
        JB    _RKRT_AJ_LP
_RKRT_AJ_DN:
        MOV   AX, OFFSET _RK_STRBUF
        POP   BX
        POP   DX
        POP   CX
        POP   DI
        RET
_RKRT_ARRJOIN ENDP

; --- _RKRT_ITOA : AX=int16 -> AX=NUMBUF ---
_RKRT_ITOA PROC NEAR
        PUSH  BX
        PUSH  CX
        PUSH  DX
        PUSH  DI
        LEA   DI, _RK_NUMBUF
        MOV   BX, AX
        TEST  AX, AX
        JNS   _RKRT_IA_POS
        MOV   BYTE PTR [DI], 2Dh
        INC   DI
        NEG   BX
_RKRT_IA_POS:
        MOV   AX, BX
        XOR   CX, CX
        MOV   BX, 10
_RKRT_IA_DV:
        XOR   DX, DX
        DIV   BX
        ADD   DL, 30h
        PUSH  DX
        INC   CX
        TEST  AX, AX
        JNZ   _RKRT_IA_DV
_RKRT_IA_PP:
        POP   DX
        MOV   [DI], DL
        INC   DI
        DEC   CX
        JNZ   _RKRT_IA_PP
        MOV   BYTE PTR [DI], 0
        MOV   AX, OFFSET _RK_NUMBUF
        POP   DI
        POP   DX
        POP   CX
        POP   BX
        RET
_RKRT_ITOA ENDP


; === Runtime HASH (TODO 16) ===

; --- _RKRT_HLOOKUP : [SP+2]=hash, [SP+4]=key -> AX ---
_RKRT_HLOOKUP PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  SI
        PUSH  DI
        PUSH  CX
        MOV   BX, [BP+4]
        MOV   DI, [BP+6]
        MOV   CX, [BX]
        ADD   BX, 2
        TEST  CX, CX
        JZ    _RKRT_HL_NF
_RKRT_HL_LOOP:
        PUSH  CX
        PUSH  BX
        MOV   SI, [BX]
_RKRT_HL_CMP:
        MOV   AL, [SI]
        MOV   AH, [DI]
        CMP   AL, AH
        JNE   _RKRT_HL_NEXT
        TEST  AL, AL
        JZ    _RKRT_HL_FOUND
        INC   SI
        INC   DI
        JMP   _RKRT_HL_CMP
_RKRT_HL_NEXT:
        MOV   DI, [BP+6]
        POP   BX
        POP   CX
        ADD   BX, 4
        DEC   CX
        JNZ   _RKRT_HL_LOOP
_RKRT_HL_NF:
        XOR   AX, AX
        JMP   _RKRT_HL_END
_RKRT_HL_FOUND:
        POP   BX
        POP   CX
        MOV   AX, [BX+2]
_RKRT_HL_END:
        POP   CX
        POP   DI
        POP   SI
        POP   BP
        RET
_RKRT_HLOOKUP ENDP

; --- _RKRT_HSTORE : BX=hash, SI=key, AX=val ---
_RKRT_HSTORE PROC NEAR
        PUSH  DI
        PUSH  CX
        PUSH  DX
        MOV   DX, AX
        MOV   DI, BX
        MOV   CX, [BX]
        ADD   BX, 2
        TEST  CX, CX
        JZ    _RKRT_HS_ADD
        PUSH  CX
_RKRT_HS_LOOP:
        PUSH  BX
        PUSH  SI
        PUSH  DI
        MOV   DI, [BX]
_RKRT_HS_CMP:
        MOV   AL, [SI]
        MOV   AH, [DI]
        CMP   AL, AH
        JNE   _RKRT_HS_NXT
        TEST  AL, AL
        JZ    _RKRT_HS_UPD
        INC   SI
        INC   DI
        JMP   _RKRT_HS_CMP
_RKRT_HS_NXT:
        POP   DI
        POP   SI
        POP   BX
        ADD   BX, 4
        DEC   CX
        JNZ   _RKRT_HS_LOOP
        POP   CX
        JMP   _RKRT_HS_ADD
_RKRT_HS_UPD:
        POP   DI
        POP   SI
        POP   BX
        MOV   [BX+2], DX
        POP   CX
        JMP   _RKRT_HS_DONE
_RKRT_HS_ADD:
        MOV   [BX], SI
        MOV   [BX+2], DX
        INC   WORD PTR [DI]
        ADD   WORD PTR [_RK_HEAPTOP], 4
_RKRT_HS_DONE:
        POP   DX
        POP   CX
        POP   DI
        RET
_RKRT_HSTORE ENDP

; --- _RKRT_HEXISTS : BX=hash, SI=key -> AX=0|1 ---
_RKRT_HEXISTS PROC NEAR
        PUSH  DI
        PUSH  CX
        MOV   CX, [BX]
        ADD   BX, 2
        TEST  CX, CX
        JZ    _RKRT_HE_NF
_RKRT_HE_LOOP:
        PUSH  CX
        PUSH  BX
        PUSH  SI
        MOV   DI, [BX]
_RKRT_HE_CMP:
        MOV   AL, [SI]
        MOV   AH, [DI]
        CMP   AL, AH
        JNE   _RKRT_HE_NXT
        TEST  AL, AL
        JZ    _RKRT_HE_YES
        INC   SI
        INC   DI
        JMP   _RKRT_HE_CMP
_RKRT_HE_NXT:
        POP   SI
        POP   BX
        POP   CX
        ADD   BX, 4
        DEC   CX
        JNZ   _RKRT_HE_LOOP
_RKRT_HE_NF:
        XOR   AX, AX
        JMP   _RKRT_HE_END
_RKRT_HE_YES:
        POP   SI
        POP   BX
        POP   CX
        MOV   AX, 1
_RKRT_HE_END:
        POP   CX
        POP   DI
        RET
_RKRT_HEXISTS ENDP

; --- _RKRT_HDELETE : BX=hash, SI=key ---
_RKRT_HDELETE PROC NEAR
        PUSH  DI
        PUSH  CX
        PUSH  DX
        MOV   DX, BX
        MOV   CX, [BX]
        ADD   BX, 2
        TEST  CX, CX
        JZ    _RKRT_HD_END
_RKRT_HD_LOOP:
        PUSH  CX
        PUSH  BX
        PUSH  SI
        MOV   DI, [BX]
_RKRT_HD_CMP:
        MOV   AL, [SI]
        MOV   AH, [DI]
        CMP   AL, AH
        JNE   _RKRT_HD_NXT
        TEST  AL, AL
        JZ    _RKRT_HD_FND
        INC   SI
        INC   DI
        JMP   _RKRT_HD_CMP
_RKRT_HD_NXT:
        POP   SI
        POP   BX
        POP   CX
        ADD   BX, 4
        DEC   CX
        JNZ   _RKRT_HD_LOOP
        JMP   _RKRT_HD_END
_RKRT_HD_FND:
        POP   SI
        POP   BX
        POP   CX
        DEC   CX
        TEST  CX, CX
        JZ    _RKRT_HD_DEC
        PUSH  SI
        MOV   SI, BX
        ADD   SI, 4
_RKRT_HD_SH:
        MOV   AX, [SI]
        MOV   [BX], AX
        MOV   AX, [SI+2]
        MOV   [BX+2], AX
        ADD   BX, 4
        ADD   SI, 4
        DEC   CX
        JNZ   _RKRT_HD_SH
        POP   SI
_RKRT_HD_DEC:
        MOV   BX, DX
        DEC   WORD PTR [BX]
        SUB   WORD PTR [_RK_HEAPTOP], 4
_RKRT_HD_END:
        POP   DX
        POP   CX
        POP   DI
        RET
_RKRT_HDELETE ENDP

; --- _RKRT_HKEYS : BX=hash -> AX=array of keys ---
_RKRT_HKEYS PROC NEAR
        PUSH  SI
        PUSH  CX
        PUSH  DI
        MOV   CX, [BX]
        MOV   DI, [_RK_HEAPTOP]
        MOV   [DI], CX
        ADD   BX, 2
        MOV   SI, DI
        ADD   SI, 2
        TEST  CX, CX
        JZ    _RKRT_HK_DN
_RKRT_HK_LP:
        MOV   AX, [BX]
        MOV   [SI], AX
        ADD   SI, 2
        ADD   BX, 4
        DEC   CX
        JNZ   _RKRT_HK_LP
_RKRT_HK_DN:
        MOV   [_RK_HEAPTOP], SI
        MOV   AX, DI
        POP   DI
        POP   CX
        POP   SI
        RET
_RKRT_HKEYS ENDP

; --- _RKRT_HVALUES : BX=hash -> AX=array of values ---
_RKRT_HVALUES PROC NEAR
        PUSH  SI
        PUSH  CX
        PUSH  DI
        MOV   CX, [BX]
        MOV   DI, [_RK_HEAPTOP]
        MOV   [DI], CX
        ADD   BX, 2
        MOV   SI, DI
        ADD   SI, 2
        TEST  CX, CX
        JZ    _RKRT_HV_DN
_RKRT_HV_LP:
        MOV   AX, [BX+2]
        MOV   [SI], AX
        ADD   SI, 2
        ADD   BX, 4
        DEC   CX
        JNZ   _RKRT_HV_LP
_RKRT_HV_DN:
        MOV   [_RK_HEAPTOP], SI
        MOV   AX, DI
        POP   DI
        POP   CX
        POP   SI
        RET
_RKRT_HVALUES ENDP

_TEXT   ENDS

_DATA   SEGMENT WORD PUBLIC 'DATA'
_RK_CRLF  DB  13,10,0
_RK_NL  DB  10,0
_RK_SPACE  DB  32,0
_RK_EMPTY  DB  0
_RK_TRUE_S  DB  84,114,117,101,0
_RK_FALSE_S  DB  70,97,108,115,101,0
_RK_NIL_S  DB  78,105,108,0
_RK_STRBUF  DB  256 DUP(0)
_RK_TMPBUF  DB  256 DUP(0)
_RK_NUMBUF  DB  12 DUP(0)
_RK_IOBUF  DB  130 DUP(0)
_RK_HEAP  DB  4096 DUP(0)
_RK_HEAPTOP  DW  0
_RK_MULTISIG  DW  0
_RKK_NOMDISP  DB  78,111,32,109,97,116,99,104,105,110,103,32,109,117,108,116,105,32,99,97,110,100,105,100,97,116,101,0
_RK_INSTPTR  DW  0
_RKK_NOMETHOD  DB  77,101,116,104,111,100,32,110,111,116,32,102,111,117,110,100,0
_RKK_NOROLE  DB  82,101,113,117,105,114,101,100,32,109,101,116,104,111,100,32,110,111,116,32,112,114,111,118,105,100,101,100,0
_RK_MATCHPTR  DW  0
_RK_MATCHEND  DW  0
_RK_MATCHOK  DW  0
_RKK_NOGRAMMAR  DB  71,114,97,109,109,97,114,32,110,111,116,32,102,111,117,110,100,0
_RKK_NOMATCH  DB  77,97,116,99,104,32,102,97,105,108,101,100,0
_RKK_1  DB  104,101,108,108,111,0
_RKV_count  DW  0
_DATA   ENDS

        END     _RKS_MAIN
