; Generated by PERL86 v1.0 - 2026-03-05
; Source : file_io_test2.pl

        .MODEL  SMALL
        .STACK  1024

_TEXT   SEGMENT WORD PUBLIC 'CODE'
        ASSUME  CS:_TEXT, DS:_DATA

_PRF_main PROC NEAR
        MOV  AX, @DATA
        MOV  DS, AX

        SUB  SP, 2
; open $fa, '>>', 'append_test.txt'
        MOV  DX, OFFSET _PRK_2
        MOV  AX, 3D01h
        INT 21h
        JC  _PRL_OPOK_3
        MOV  BX, AX
        MOV  AX, 4202h
        MOV  CX, 0
        MOV  DX, 0
        INT 21h
        MOV  WORD PTR [BP-2], BX
_PRL_OPOK_3:
        MOV  SI, OFFSET _PRK_4
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, WORD PTR [BP-2]
        CALL  _PRRT_PRINT
; close $fa
        MOV  BX, WORD PTR [BP-2]
        MOV  AH, 3Eh
        INT 21h
        SUB  SP, 2
; open $fc, '<', 'append_test.txt'
        MOV  DX, OFFSET _PRK_2
        MOV  AX, 3D00h
        INT 21h
        JC  _PRL_OPOK_6
        MOV  WORD PTR [BP-4], AX
_PRL_OPOK_6:
        SUB  SP, 2
; init my $e1
        MOV  WORD PTR [BP-6], 0
        MOV  BX, WORD PTR [BP-4]
        MOV  AH, 3Fh
        MOV  CX, 1
        MOV  DX, OFFSET _PRRT_FHBUF
        INT 21h
        JC  _PRL_EOFYES_8
        TEST  AX, AX
        JZ  _PRL_EOFYES_8
        MOV  AX, 4201h
        MOV  CX, 0FFFFh
        MOV  DX, 0FFFFh
        INT 21h
        MOV  AX, 0
        JMP  _PRL_EOFEND_9
_PRL_EOFYES_8:
        MOV  AX, 1
_PRL_EOFEND_9:
        MOV  WORD PTR [BP-6], AX
        SUB  SP, 2
; init my $line
        MOV  WORD PTR [BP-8], 0
        MOV  BX, WORD PTR [BP-4]
        CALL  _PRRT_READLINE
        MOV  WORD PTR [BP-8], AX
        SUB  SP, 2
; init my $e2
        MOV  WORD PTR [BP-10], 0
        MOV  BX, WORD PTR [BP-4]
        MOV  AH, 3Fh
        MOV  CX, 1
        MOV  DX, OFFSET _PRRT_FHBUF
        INT 21h
        JC  _PRL_EOFYES_12
        TEST  AX, AX
        JZ  _PRL_EOFYES_12
        MOV  AX, 4201h
        MOV  CX, 0FFFFh
        MOV  DX, 0FFFFh
        INT 21h
        MOV  AX, 0
        JMP  _PRL_EOFEND_13
_PRL_EOFYES_12:
        MOV  AX, 1
_PRL_EOFEND_13:
        MOV  WORD PTR [BP-10], AX
; close $fc
        MOV  BX, WORD PTR [BP-4]
        MOV  AH, 3Eh
        INT 21h
        MOV  SI, OFFSET _PRK_14
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        MOV  AX, WORD PTR [BP-6]
        MOV  DI, OFFSET _PRRT_IBUF
        CALL  _PRRT_ITOA
        MOV  SI, DI
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        MOV  SI, OFFSET _PRK_15
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        MOV  AX, WORD PTR [BP-10]
        MOV  DI, OFFSET _PRRT_IBUF
        CALL  _PRRT_ITOA
        MOV  SI, DI
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT

; Fin du script Perl - sortie implicite code 0
        MOV  AX, 4C00h
        INT  21h
_PRF_main ENDP


; === Runtime PERL86 - TODO 19 ===

_PRRT_REMATCH PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  CX
        PUSH  DX
        MOV   BX, SI
_PRRT_RML:
        MOV   AL, [BX]
        TEST  AL, AL
        JZ    _PRRT_RMFL
        MOV   SI, BX
        MOV   CX, DI
_PRRT_RMC:
        MOV   AL, [CX]
        TEST  AL, AL
        JZ    _PRRT_RMOK
        MOV   DL, [SI]
        CMP   AL, DL
        JNE   _PRRT_RMN
        INC   SI
        INC   CX
        JMP   _PRRT_RMC
_PRRT_RMN:
        INC   BX
        JMP   _PRRT_RML
_PRRT_RMOK:
        MOV   AX, 1
        JMP   _PRRT_RMDN
_PRRT_RMFL:
        XOR   AX, AX
_PRRT_RMDN:
        POP   DX
        POP   CX
        POP   BX
        POP   DI
        POP   SI
        POP   BP
        RET
_PRRT_REMATCH ENDP

_PRRT_RESUB PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  CX
        PUSH  DX
        MOV   BX, SI
_PRRT_RSL:
        MOV   AL, [BX]
        TEST  AL, AL
        JZ    _PRRT_RSFL
        MOV   SI, BX
        MOV   CX, DI
_PRRT_RSC:
        MOV   AL, [CX]
        TEST  AL, AL
        JZ    _PRRT_RSOK
        MOV   DL, [SI]
        CMP   AL, DL
        JNE   _PRRT_RSN
        INC   SI
        INC   CX
        JMP   _PRRT_RSC
_PRRT_RSN:
        INC   BX
        JMP   _PRRT_RSL
_PRRT_RSOK:
        MOV   SI, BX
        MOV   CX, [BP-6]
_PRRT_RSCPY:
        MOV   AL, [CX]
        TEST  AL, AL
        JZ    _PRRT_RS0
        MOV   [SI], AL
        INC   SI
        INC   CX
        JMP   _PRRT_RSCPY
_PRRT_RS0:
        MOV   BYTE PTR [SI], 0
        MOV   AX, 1
        JMP   _PRRT_RSDN
_PRRT_RSFL:
        XOR   AX, AX
_PRRT_RSDN:
        POP   DX
        POP   CX
        POP   BX
        POP   DI
        POP   SI
        POP   BP
        RET
_PRRT_RESUB ENDP

_PRRT_ABS PROC NEAR
        TEST  AX, AX
        JNS   _PRRT_ABS_OK
        NEG   AX
_PRRT_ABS_OK:
        RET
_PRRT_ABS ENDP

_PRRT_ORD PROC NEAR
        XOR   AX, AX
        MOV   AL, [SI]
        RET
_PRRT_ORD ENDP

_PRRT_CHR PROC NEAR
        MOV   [DI], AL
        PUSH  BX
        MOV   BX, DI
        INC   BX
        MOV   BYTE PTR [BX], 0
        POP   BX
        RET
_PRRT_CHR ENDP

_PRRT_CHOMP PROC NEAR
        PUSH  SI
        PUSH  DI
        MOV   DI, SI
_PRRT_CHML:
        MOV   AL, [DI]
        TEST  AL, AL
        JZ    _PRRT_CHME
        INC   DI
        JMP   _PRRT_CHML
_PRRT_CHME:
        CMP   DI, SI
        JE    _PRRT_CHMNO
        DEC   DI
        MOV   AL, [DI]
        CMP   AL, 10
        JNE   _PRRT_CHMNO
        MOV   BYTE PTR [DI], 0
        MOV   AX, 1
        JMP   _PRRT_CHMRN
_PRRT_CHMNO:
        XOR   AX, AX
_PRRT_CHMRN:
        POP   DI
        POP   SI
        RET
_PRRT_CHOMP ENDP

_PRRT_CHOP PROC NEAR
        PUSH  SI
        PUSH  DI
        MOV   DI, SI
_PRRT_CHPL:
        MOV   AL, [DI]
        TEST  AL, AL
        JZ    _PRRT_CHPE
        INC   DI
        JMP   _PRRT_CHPL
_PRRT_CHPE:
        XOR   AX, AX
        CMP   DI, SI
        JE    _PRRT_CHPRN
        DEC   DI
        MOV   AL, [DI]
        MOV   BYTE PTR [DI], 0
_PRRT_CHPRN:
        POP   DI
        POP   SI
        RET
_PRRT_CHOP ENDP

_PRRT_UC PROC NEAR
        PUSH  SI
        PUSH  DI
_PRRT_UCL:
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_UCE
        CMP   AL, 97
        JL    _PRRT_UCCP
        CMP   AL, 122
        JG    _PRRT_UCCP
        SUB   AL, 32
_PRRT_UCCP:
        MOV   [DI], AL
        INC   SI
        INC   DI
        JMP   _PRRT_UCL
_PRRT_UCE:
        MOV   BYTE PTR [DI], 0
        POP   DI
        POP   SI
        RET
_PRRT_UC ENDP

_PRRT_LC PROC NEAR
        PUSH  SI
        PUSH  DI
_PRRT_LCL:
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_LCE
        CMP   AL, 65
        JL    _PRRT_LCCP
        CMP   AL, 90
        JG    _PRRT_LCCP
        ADD   AL, 32
_PRRT_LCCP:
        MOV   [DI], AL
        INC   SI
        INC   DI
        JMP   _PRRT_LCL
_PRRT_LCE:
        MOV   BYTE PTR [DI], 0
        POP   DI
        POP   SI
        RET
_PRRT_LC ENDP

_PRRT_UCFIRST PROC NEAR
        PUSH  SI
        PUSH  DI
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_UCFE
        CMP   AL, 97
        JL    _PRRT_UCFC
        CMP   AL, 122
        JG    _PRRT_UCFC
        SUB   AL, 32
_PRRT_UCFC:
        MOV   [DI], AL
        INC   SI
        INC   DI
_PRRT_UCFR:
        MOV   AL, [SI]
        MOV   [DI], AL
        TEST  AL, AL
        JZ    _PRRT_UCFE
        INC   SI
        INC   DI
        JMP   _PRRT_UCFR
_PRRT_UCFE:
        POP   DI
        POP   SI
        RET
_PRRT_UCFIRST ENDP

_PRRT_LCFIRST PROC NEAR
        PUSH  SI
        PUSH  DI
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_LCFE
        CMP   AL, 65
        JL    _PRRT_LCFC
        CMP   AL, 90
        JG    _PRRT_LCFC
        ADD   AL, 32
_PRRT_LCFC:
        MOV   [DI], AL
        INC   SI
        INC   DI
_PRRT_LCFR:
        MOV   AL, [SI]
        MOV   [DI], AL
        TEST  AL, AL
        JZ    _PRRT_LCFE
        INC   SI
        INC   DI
        JMP   _PRRT_LCFR
_PRRT_LCFE:
        POP   DI
        POP   SI
        RET
_PRRT_LCFIRST ENDP

_PRRT_INDEX PROC NEAR
        PUSH  BP
        MOV   BP, SP
        SUB   SP, 2
        MOV   WORD PTR [BP-2], DI
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  DX
        MOV   BX, SI
        XOR   DX, DX
_PRRT_IDXL:
        MOV   AL, [BX]
        TEST  AL, AL
        JZ    _PRRT_IDXFL
        MOV   SI, BX
        MOV   DI, WORD PTR [BP-2]
_PRRT_IDXC:
        MOV   AL, [DI]
        TEST  AL, AL
        JZ    _PRRT_IDXOK
        MOV   AH, [SI]
        CMP   AL, AH
        JNE   _PRRT_IDXN
        INC   SI
        INC   DI
        JMP   _PRRT_IDXC
_PRRT_IDXN:
        INC   BX
        INC   DX
        JMP   _PRRT_IDXL
_PRRT_IDXOK:
        MOV   AX, DX
        JMP   _PRRT_IDXDN
_PRRT_IDXFL:
        MOV   AX, 0FFFFh
_PRRT_IDXDN:
        POP   DX
        POP   BX
        POP   DI
        POP   SI
        ADD   SP, 2
        POP   BP
        RET
_PRRT_INDEX ENDP

_PRRT_RINDEX PROC NEAR
        PUSH  BP
        MOV   BP, SP
        SUB   SP, 2
        MOV   WORD PTR [BP-2], DI
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  DX
        MOV   BX, SI
        XOR   DX, DX
        MOV   AX, 0FFFFh
_PRRT_RIL:
        MOV   AL, [BX]
        TEST  AL, AL
        JZ    _PRRT_RIDN
        MOV   SI, BX
        MOV   DI, WORD PTR [BP-2]
_PRRT_RIC:
        MOV   AL, [DI]
        TEST  AL, AL
        JZ    _PRRT_RIOK
        MOV   AH, [SI]
        CMP   AL, AH
        JNE   _PRRT_RIN
        INC   SI
        INC   DI
        JMP   _PRRT_RIC
_PRRT_RIN:
        INC   BX
        INC   DX
        JMP   _PRRT_RIL
_PRRT_RIOK:
        MOV   AX, DX
        INC   BX
        INC   DX
        JMP   _PRRT_RIL
_PRRT_RIDN:
        POP   DX
        POP   BX
        POP   DI
        POP   SI
        ADD   SP, 2
        POP   BP
        RET
_PRRT_RINDEX ENDP

_PRRT_SUBSTR PROC NEAR
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  CX
        TEST  BX, BX
        JZ    _PRRT_SUBST
_PRRT_SUBADV:
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_SUBEN
        INC   SI
        DEC   BX
        JNZ   _PRRT_SUBADV
_PRRT_SUBST:
_PRRT_SUBCPY:
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_SUBEN
        CMP   CX, 0FFFFh
        JE    _PRRT_SUBND
        TEST  CX, CX
        JZ    _PRRT_SUBEN
        DEC   CX
_PRRT_SUBND:
        MOV   [DI], AL
        INC   SI
        INC   DI
        JMP   _PRRT_SUBCPY
_PRRT_SUBEN:
        MOV   BYTE PTR [DI], 0
        POP   CX
        POP   BX
        POP   DI
        POP   SI
        RET
_PRRT_SUBSTR ENDP

_PRRT_HEX2INT PROC NEAR
        PUSH  SI
        PUSH  BX
        XOR   AX, AX
        XOR   BX, BX
        MOV   BL, [SI]
        CMP   BL, 48
        JNE   _PRRT_HIL
        MOV   BL, [SI+1]
        CMP   BL, 120
        JE    _PRRT_HISKIP
        CMP   BL, 88
        JNE   _PRRT_HIL
_PRRT_HISKIP:
        INC   SI
        INC   SI
_PRRT_HIL:
        XOR   BX, BX
        MOV   BL, [SI]
        TEST  BL, BL
        JZ    _PRRT_HIDN
        CMP   BL, 48
        JL    _PRRT_HIDN
        CMP   BL, 57
        JLE   _PRRT_HIDIG
        CMP   BL, 65
        JL    _PRRT_HIDN
        CMP   BL, 70
        JLE   _PRRT_HIHEX
        CMP   BL, 97
        JL    _PRRT_HIDN
        CMP   BL, 102
        JG    _PRRT_HIDN
        SUB   BL, 87
        JMP   _PRRT_HIACC
_PRRT_HIHEX:
        SUB   BL, 55
        JMP   _PRRT_HIACC
_PRRT_HIDIG:
        SUB   BL, 48
_PRRT_HIACC:
        SHL   AX, 1
        SHL   AX, 1
        SHL   AX, 1
        SHL   AX, 1
        OR    AX, BX
        INC   SI
        JMP   _PRRT_HIL
_PRRT_HIDN:
        POP   BX
        POP   SI
        RET
_PRRT_HEX2INT ENDP

_PRRT_OCT2INT PROC NEAR
        PUSH  SI
        PUSH  BX
        XOR   AX, AX
_PRRT_OIL:
        XOR   BX, BX
        MOV   BL, [SI]
        TEST  BL, BL
        JZ    _PRRT_OIDN
        SUB   BL, 48
        JL    _PRRT_OIDN
        CMP   BL, 7
        JG    _PRRT_OIDN
        SHL   AX, 1
        SHL   AX, 1
        SHL   AX, 1
        OR    AX, BX
        INC   SI
        JMP   _PRRT_OIL
_PRRT_OIDN:
        POP   BX
        POP   SI
        RET
_PRRT_OCT2INT ENDP

_PRRT_READLINE PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  BX
        PUSH  SI
        PUSH  DI
        MOV   DI, OFFSET _PRRT_FHBUF
        MOV   SI, 0
_PRRT_RLL:
        CMP   SI, 0FEh
        JGE   _PRRT_RLDON
        MOV   BX, WORD PTR [BP-2]
        MOV   AH, 3Fh
        MOV   CX, 1
        MOV   DX, DI
        INT   21h
        JC    _PRRT_RLEOF
        TEST  AX, AX
        JZ    _PRRT_RLEOF
        MOV   AL, BYTE PTR [DI]
        CMP   AL, 0Ah
        JE    _PRRT_RLDON
        CMP   AL, 0Dh
        JE    _PRRT_RLDON
        INC   DI
        INC   SI
        JMP   _PRRT_RLL
_PRRT_RLEOF:
        TEST  SI, SI
        JZ    _PRRT_RLNUL
        JMP   _PRRT_RLDON
_PRRT_RLNUL:
        XOR   AX, AX
        JMP   _PRRT_RLRET
_PRRT_RLDON:
        MOV   BYTE PTR [DI], 0
        MOV   AX, OFFSET _PRRT_FHBUF
_PRRT_RLRET:
        POP   DI
        POP   SI
        POP   BX
        POP   BP
        RET
_PRRT_READLINE ENDP

_TEXT   ENDS

_DATA   SEGMENT WORD PUBLIC 'DATA'

_PRK_2:
        DB  'append_test.txt'0

_PRK_4:
        DB  'Texte appende'10,0

_PRRT_FHBUF:
        DW  128 DUP(0)

_PRK_14:
        DB  'eof avant lectur'
        DB  'e: '0

_PRRT_IBUF:
        DW  8 DUP(0)

_PRK_15:
        DB  'eof apres lectur'
        DB  'e: '0

_PRCAP_1:
        DW  0
_PRCAP_2:
        DW  0

_DATA   ENDS

        END     _PRF_main
