; Generated by PERL86 v1.0 - 2026-03-05
; Source : regex_test2.pl

        .MODEL  SMALL
        .STACK  1024

_TEXT   SEGMENT WORD PUBLIC 'CODE'
        ASSUME  CS:_TEXT, DS:_DATA

_PRF_main PROC NEAR
        MOV  AX, @DATA
        MOV  DS, AX

        SUB  SP, 2
; init my $s
        MOV  WORD PTR [BP-2], 0
        MOV  AX, OFFSET _PRK_2
        MOV  WORD PTR [BP-2], AX
        MOV  AX, WORD PTR [BP-2]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P1
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        JZ  _PRL_ELSE_4
        MOV  SI, OFFSET _PRK_5
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_3
_PRL_ELSE_4:
        MOV  SI, OFFSET _PRK_6
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
_PRL_ENDIF_3:
        MOV  AX, WORD PTR [BP-2]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P2
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        JZ  _PRL_ELSE_8
        MOV  SI, OFFSET _PRK_9
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_7
_PRL_ELSE_8:
        MOV  SI, OFFSET _PRK_10
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
_PRL_ENDIF_7:
        MOV  AX, WORD PTR [BP-2]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P3
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        SETZ  AL
        MOVZX  AX, AL
        TEST  AX, AX
        JZ  _PRL_ELSE_12
        MOV  SI, OFFSET _PRK_13
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_11
_PRL_ELSE_12:
        MOV  SI, OFFSET _PRK_14
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
_PRL_ENDIF_11:
        MOV  AX, WORD PTR [BP-2]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P4
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        SETZ  AL
        MOVZX  AX, AL
        TEST  AX, AX
        JZ  _PRL_ELSE_16
        MOV  SI, OFFSET _PRK_17
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_15
_PRL_ELSE_16:
        MOV  SI, OFFSET _PRK_18
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
_PRL_ENDIF_15:
        SUB  SP, 2
; init my $r
        MOV  WORD PTR [BP-4], 0
        MOV  AX, 42
        MOV  WORD PTR [BP-4], AX
        MOV  AX, WORD PTR [BP-4]
        PUSH  AX
        MOV  AX, 42
        POP  BX
        CMP  BX, AX
        SETE  AL
        MOVZX  AX, AL
        TEST  AX, AX
        JZ  _PRL_ELSE_21
        MOV  SI, OFFSET _PRK_22
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_20
_PRL_ELSE_21:
_PRL_ENDIF_20:
        MOV  SI, OFFSET _PRK_23
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT

; Fin du script Perl - sortie implicite code 0
        MOV  AX, 4C00h
        INT  21h
_PRF_main ENDP


; === Runtime PERL86 - TODO 19 ===

_PRRT_REMATCH PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  CX
        PUSH  DX
        MOV   BX, SI
_PRRT_RML:
        MOV   AL, [BX]
        TEST  AL, AL
        JZ    _PRRT_RMFL
        MOV   SI, BX
        MOV   CX, DI
_PRRT_RMC:
        MOV   AL, [CX]
        TEST  AL, AL
        JZ    _PRRT_RMOK
        MOV   DL, [SI]
        CMP   AL, DL
        JNE   _PRRT_RMN
        INC   SI
        INC   CX
        JMP   _PRRT_RMC
_PRRT_RMN:
        INC   BX
        JMP   _PRRT_RML
_PRRT_RMOK:
        MOV   AX, 1
        JMP   _PRRT_RMDN
_PRRT_RMFL:
        XOR   AX, AX
_PRRT_RMDN:
        POP   DX
        POP   CX
        POP   BX
        POP   DI
        POP   SI
        POP   BP
        RET
_PRRT_REMATCH ENDP

_PRRT_RESUB PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  CX
        PUSH  DX
        MOV   BX, SI
_PRRT_RSL:
        MOV   AL, [BX]
        TEST  AL, AL
        JZ    _PRRT_RSFL
        MOV   SI, BX
        MOV   CX, DI
_PRRT_RSC:
        MOV   AL, [CX]
        TEST  AL, AL
        JZ    _PRRT_RSOK
        MOV   DL, [SI]
        CMP   AL, DL
        JNE   _PRRT_RSN
        INC   SI
        INC   CX
        JMP   _PRRT_RSC
_PRRT_RSN:
        INC   BX
        JMP   _PRRT_RSL
_PRRT_RSOK:
        MOV   SI, BX
        MOV   CX, [BP-6]
_PRRT_RSCPY:
        MOV   AL, [CX]
        TEST  AL, AL
        JZ    _PRRT_RS0
        MOV   [SI], AL
        INC   SI
        INC   CX
        JMP   _PRRT_RSCPY
_PRRT_RS0:
        MOV   BYTE PTR [SI], 0
        MOV   AX, 1
        JMP   _PRRT_RSDN
_PRRT_RSFL:
        XOR   AX, AX
_PRRT_RSDN:
        POP   DX
        POP   CX
        POP   BX
        POP   DI
        POP   SI
        POP   BP
        RET
_PRRT_RESUB ENDP

_TEXT   ENDS

_DATA   SEGMENT WORD PUBLIC 'DATA'

_PRK_2:
        DB  'hello world'0

_PRRX_P1:
        DB  'world'0

_PRK_5:
        DB  'TEST1 OK: =~ wor'
        DB  'ld trouve'10,0

_PRK_6:
        DB  'TEST1 FAIL'10,0

_PRRX_P2:
        DB  'xyz'0

_PRK_9:
        DB  'TEST2 FAIL'10,0

_PRK_10:
        DB  'TEST2 OK: =~ xyz'
        DB  ' pas trouve'10,0

_PRRX_P3:
        DB  'xyz'0

_PRK_13:
        DB  'TEST3 OK: !~ xyz'
        DB  ' absent'10,0

_PRK_14:
        DB  'TEST3 FAIL'10,0

_PRRX_P4:
        DB  'world'0

_PRK_17:
        DB  'TEST4 FAIL'10,0

_PRK_18:
        DB  'TEST4 OK: !~ wor'
        DB  'ld present'10,0

_PRK_22:
        DB  'TEST5 OK: variab'
        DB  'le numerique ok'10
        DB  0

_PRK_23:
        DB  'DONE'10,0

_PRCAP_1:
        DW  0
_PRCAP_2:
        DW  0

_DATA   ENDS

        END     _PRF_main
