; Generated by PERL86 v1.0 - 2026-03-05
; Source : SAMPLES\PERL\regex.pl

        .MODEL  SMALL
        .STACK  1024

_TEXT   SEGMENT WORD PUBLIC 'CODE'
        ASSUME  CS:_TEXT, DS:_DATA

_PRF_main PROC NEAR
        MOV  AX, @DATA
        MOV  DS, AX

; use strict: mode strict active
; use warnings: mode warnings active
        SUB  SP, 2
; init my $str
        MOV  WORD PTR [BP-2], 0
        MOV  AX, OFFSET _PRK_2
        MOV  WORD PTR [BP-2], AX
        MOV  AX, WORD PTR [BP-2]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P1
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        JZ  _PRL_ELSE_4
        MOV  SI, OFFSET _PRK_5
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_3
_PRL_ELSE_4:
        MOV  SI, OFFSET _PRK_6
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
_PRL_ENDIF_3:
        MOV  AX, WORD PTR [BP-2]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P2
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        JZ  _PRL_ELSE_8
        MOV  SI, OFFSET _PRK_9
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_7
_PRL_ELSE_8:
_PRL_ENDIF_7:
        MOV  AX, WORD PTR [BP-2]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P3
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        SETZ  AL
        MOVZX  AX, AL
        TEST  AX, AX
        JZ  _PRL_ELSE_11
        MOV  SI, OFFSET _PRK_12
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_10
_PRL_ELSE_11:
_PRL_ENDIF_10:
        SUB  SP, 2
; init my $email
        MOV  WORD PTR [BP-4], 0
        MOV  AX, OFFSET _PRK_14
        MOV  WORD PTR [BP-4], AX
        MOV  AX, WORD PTR [BP-4]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P4
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        JZ  _PRL_ELSE_16
        MOV  SI, OFFSET _PRK_17
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_15
_PRL_ELSE_16:
_PRL_ENDIF_15:
        SUB  SP, 2
; init my $msg
        MOV  WORD PTR [BP-6], 0
        MOV  AX, OFFSET _PRK_19
        MOV  WORD PTR [BP-6], AX
        JMP  _PRL_SMCND_21
_PRL_SMBOD_20:
        MOV  AX, WORD PTR [BP-6]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P5
        MOV  BX, OFFSET _PRRX_R5
        CALL  _PRRT_RESUB
; s/pat/repl/ : AX=1 si substitution effectuee
        MOV  WORD PTR [_PRCAP_1], AX
        JMP  _PRL_SMEND_22
_PRL_SMCND_21:
        JMP  _PRL_SMBOD_20
_PRL_SMEND_22:
        MOV  AX, WORD PTR [BP-6]
        MOV  DI, OFFSET _PRRT_IBUF
        CALL  _PRRT_ITOA
        MOV  SI, DI
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        MOV  SI, OFFSET _PRK_23
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        SUB  SP, 2
; init my $code
        MOV  WORD PTR [BP-8], 0
        MOV  AX, OFFSET _PRK_25
        MOV  WORD PTR [BP-8], AX
        JMP  _PRL_SMCND_27
_PRL_SMBOD_26:
        MOV  AX, WORD PTR [BP-8]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P6
        MOV  BX, OFFSET _PRRX_R6
        CALL  _PRRT_RESUB
; s/pat/repl/ : AX=1 si substitution effectuee
        MOV  WORD PTR [_PRCAP_1], AX
        JMP  _PRL_SMEND_28
_PRL_SMCND_27:
        JMP  _PRL_SMBOD_26
_PRL_SMEND_28:
        MOV  AX, WORD PTR [BP-8]
        MOV  DI, OFFSET _PRRT_IBUF
        CALL  _PRRT_ITOA
        MOV  SI, DI
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        MOV  SI, OFFSET _PRK_23
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        SUB  SP, 2
; init my $url
        MOV  WORD PTR [BP-10], 0
        MOV  AX, OFFSET _PRK_30
        MOV  WORD PTR [BP-10], AX
        MOV  AX, WORD PTR [BP-10]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P7
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        JZ  _PRL_ELSE_32
        MOV  SI, OFFSET _PRK_33
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_31
_PRL_ELSE_32:
_PRL_ENDIF_31:
        MOV  AX, WORD PTR [BP-10]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P8
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        SETZ  AL
        MOVZX  AX, AL
        TEST  AX, AX
        JZ  _PRL_ELSE_35
        MOV  SI, OFFSET _PRK_36
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_34
_PRL_ELSE_35:
_PRL_ENDIF_34:
        SUB  SP, 2
; init my $nom
        MOV  WORD PTR [BP-12], 0
        MOV  AX, OFFSET _PRK_38
        MOV  WORD PTR [BP-12], AX
        MOV  AX, WORD PTR [BP-12]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P9
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        JZ  _PRL_ELSE_40
        JMP  _PRL_SMCND_42
_PRL_SMBOD_41:
        MOV  AX, WORD PTR [BP-12]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P10
        MOV  BX, OFFSET _PRRX_R10
        CALL  _PRRT_RESUB
; s/pat/repl/ : AX=1 si substitution effectuee
        MOV  WORD PTR [_PRCAP_1], AX
        JMP  _PRL_SMEND_43
_PRL_SMCND_42:
        JMP  _PRL_SMBOD_41
_PRL_SMEND_43:
        MOV  AX, WORD PTR [BP-12]
        MOV  DI, OFFSET _PRRT_IBUF
        CALL  _PRRT_ITOA
        MOV  SI, DI
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        MOV  SI, OFFSET _PRK_23
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_39
_PRL_ELSE_40:
_PRL_ENDIF_39:
        SUB  SP, 2
; init my $vide
        MOV  WORD PTR [BP-14], 0
        MOV  AX, OFFSET _PRK_45
        MOV  WORD PTR [BP-14], AX
        MOV  AX, WORD PTR [BP-14]
        MOV  SI, AX
        MOV  DI, OFFSET _PRRX_P11
        CALL  _PRRT_REMATCH
; /pat/ : AX=1 si trouve
        MOV  WORD PTR [_PRCAP_1], AX
        TEST  AX, AX
        JZ  _PRL_ELSE_47
        MOV  SI, OFFSET _PRK_48
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
        JMP  _PRL_ENDIF_46
_PRL_ELSE_47:
        MOV  SI, OFFSET _PRK_49
        CALL  _PRRT_STRLEN
        MOV  CX, AX
        MOV  BX, 1
        CALL  _PRRT_PRINT
_PRL_ENDIF_46:

; Fin du script Perl - sortie implicite code 0
        MOV  AX, 4C00h
        INT  21h
_PRF_main ENDP


; === Runtime PERL86 - TODO 19/24 ===

_PRRT_REMATCH PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  CX
        PUSH  DX
        MOV   BX, SI
_PRRT_RML:
        MOV   AL, [BX]
        TEST  AL, AL
        JZ    _PRRT_RMFL
        MOV   SI, BX
        MOV   CX, DI
_PRRT_RMC:
        MOV   AL, [CX]
        TEST  AL, AL
        JZ    _PRRT_RMOK
        MOV   DL, [SI]
        CMP   AL, DL
        JNE   _PRRT_RMN
        INC   SI
        INC   CX
        JMP   _PRRT_RMC
_PRRT_RMN:
        INC   BX
        JMP   _PRRT_RML
_PRRT_RMOK:
        MOV   AX, 1
        JMP   _PRRT_RMDN
_PRRT_RMFL:
        XOR   AX, AX
_PRRT_RMDN:
        POP   DX
        POP   CX
        POP   BX
        POP   DI
        POP   SI
        POP   BP
        RET
_PRRT_REMATCH ENDP

_PRRT_RESUB PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  CX
        PUSH  DX
        MOV   BX, SI
_PRRT_RSL:
        MOV   AL, [BX]
        TEST  AL, AL
        JZ    _PRRT_RSFL
        MOV   SI, BX
        MOV   CX, DI
_PRRT_RSC:
        MOV   AL, [CX]
        TEST  AL, AL
        JZ    _PRRT_RSOK
        MOV   DL, [SI]
        CMP   AL, DL
        JNE   _PRRT_RSN
        INC   SI
        INC   CX
        JMP   _PRRT_RSC
_PRRT_RSN:
        INC   BX
        JMP   _PRRT_RSL
_PRRT_RSOK:
        MOV   SI, BX
        MOV   CX, [BP-6]
_PRRT_RSCPY:
        MOV   AL, [CX]
        TEST  AL, AL
        JZ    _PRRT_RS0
        MOV   [SI], AL
        INC   SI
        INC   CX
        JMP   _PRRT_RSCPY
_PRRT_RS0:
        MOV   BYTE PTR [SI], 0
        MOV   AX, 1
        JMP   _PRRT_RSDN
_PRRT_RSFL:
        XOR   AX, AX
_PRRT_RSDN:
        POP   DX
        POP   CX
        POP   BX
        POP   DI
        POP   SI
        POP   BP
        RET
_PRRT_RESUB ENDP

_PRRT_ABS PROC NEAR
        TEST  AX, AX
        JNS   _PRRT_ABS_OK
        NEG   AX
_PRRT_ABS_OK:
        RET
_PRRT_ABS ENDP

_PRRT_ORD PROC NEAR
        XOR   AX, AX
        MOV   AL, [SI]
        RET
_PRRT_ORD ENDP

_PRRT_CHR PROC NEAR
        MOV   [DI], AL
        PUSH  BX
        MOV   BX, DI
        INC   BX
        MOV   BYTE PTR [BX], 0
        POP   BX
        RET
_PRRT_CHR ENDP

_PRRT_CHOMP PROC NEAR
        PUSH  SI
        PUSH  DI
        MOV   DI, SI
_PRRT_CHML:
        MOV   AL, [DI]
        TEST  AL, AL
        JZ    _PRRT_CHME
        INC   DI
        JMP   _PRRT_CHML
_PRRT_CHME:
        CMP   DI, SI
        JE    _PRRT_CHMNO
        DEC   DI
        MOV   AL, [DI]
        CMP   AL, 10
        JNE   _PRRT_CHMNO
        MOV   BYTE PTR [DI], 0
        MOV   AX, 1
        JMP   _PRRT_CHMRN
_PRRT_CHMNO:
        XOR   AX, AX
_PRRT_CHMRN:
        POP   DI
        POP   SI
        RET
_PRRT_CHOMP ENDP

_PRRT_CHOP PROC NEAR
        PUSH  SI
        PUSH  DI
        MOV   DI, SI
_PRRT_CHPL:
        MOV   AL, [DI]
        TEST  AL, AL
        JZ    _PRRT_CHPE
        INC   DI
        JMP   _PRRT_CHPL
_PRRT_CHPE:
        XOR   AX, AX
        CMP   DI, SI
        JE    _PRRT_CHPRN
        DEC   DI
        MOV   AL, [DI]
        MOV   BYTE PTR [DI], 0
_PRRT_CHPRN:
        POP   DI
        POP   SI
        RET
_PRRT_CHOP ENDP

_PRRT_UC PROC NEAR
        PUSH  SI
        PUSH  DI
_PRRT_UCL:
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_UCE
        CMP   AL, 97
        JL    _PRRT_UCCP
        CMP   AL, 122
        JG    _PRRT_UCCP
        SUB   AL, 32
_PRRT_UCCP:
        MOV   [DI], AL
        INC   SI
        INC   DI
        JMP   _PRRT_UCL
_PRRT_UCE:
        MOV   BYTE PTR [DI], 0
        POP   DI
        POP   SI
        RET
_PRRT_UC ENDP

_PRRT_LC PROC NEAR
        PUSH  SI
        PUSH  DI
_PRRT_LCL:
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_LCE
        CMP   AL, 65
        JL    _PRRT_LCCP
        CMP   AL, 90
        JG    _PRRT_LCCP
        ADD   AL, 32
_PRRT_LCCP:
        MOV   [DI], AL
        INC   SI
        INC   DI
        JMP   _PRRT_LCL
_PRRT_LCE:
        MOV   BYTE PTR [DI], 0
        POP   DI
        POP   SI
        RET
_PRRT_LC ENDP

_PRRT_UCFIRST PROC NEAR
        PUSH  SI
        PUSH  DI
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_UCFE
        CMP   AL, 97
        JL    _PRRT_UCFC
        CMP   AL, 122
        JG    _PRRT_UCFC
        SUB   AL, 32
_PRRT_UCFC:
        MOV   [DI], AL
        INC   SI
        INC   DI
_PRRT_UCFR:
        MOV   AL, [SI]
        MOV   [DI], AL
        TEST  AL, AL
        JZ    _PRRT_UCFE
        INC   SI
        INC   DI
        JMP   _PRRT_UCFR
_PRRT_UCFE:
        POP   DI
        POP   SI
        RET
_PRRT_UCFIRST ENDP

_PRRT_LCFIRST PROC NEAR
        PUSH  SI
        PUSH  DI
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_LCFE
        CMP   AL, 65
        JL    _PRRT_LCFC
        CMP   AL, 90
        JG    _PRRT_LCFC
        ADD   AL, 32
_PRRT_LCFC:
        MOV   [DI], AL
        INC   SI
        INC   DI
_PRRT_LCFR:
        MOV   AL, [SI]
        MOV   [DI], AL
        TEST  AL, AL
        JZ    _PRRT_LCFE
        INC   SI
        INC   DI
        JMP   _PRRT_LCFR
_PRRT_LCFE:
        POP   DI
        POP   SI
        RET
_PRRT_LCFIRST ENDP

_PRRT_INDEX PROC NEAR
        PUSH  BP
        MOV   BP, SP
        SUB   SP, 2
        MOV   WORD PTR [BP-2], DI
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  DX
        MOV   BX, SI
        XOR   DX, DX
_PRRT_IDXL:
        MOV   AL, [BX]
        TEST  AL, AL
        JZ    _PRRT_IDXFL
        MOV   SI, BX
        MOV   DI, WORD PTR [BP-2]
_PRRT_IDXC:
        MOV   AL, [DI]
        TEST  AL, AL
        JZ    _PRRT_IDXOK
        MOV   AH, [SI]
        CMP   AL, AH
        JNE   _PRRT_IDXN
        INC   SI
        INC   DI
        JMP   _PRRT_IDXC
_PRRT_IDXN:
        INC   BX
        INC   DX
        JMP   _PRRT_IDXL
_PRRT_IDXOK:
        MOV   AX, DX
        JMP   _PRRT_IDXDN
_PRRT_IDXFL:
        MOV   AX, 0FFFFh
_PRRT_IDXDN:
        POP   DX
        POP   BX
        POP   DI
        POP   SI
        ADD   SP, 2
        POP   BP
        RET
_PRRT_INDEX ENDP

_PRRT_RINDEX PROC NEAR
        PUSH  BP
        MOV   BP, SP
        SUB   SP, 2
        MOV   WORD PTR [BP-2], DI
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  DX
        MOV   BX, SI
        XOR   DX, DX
        MOV   AX, 0FFFFh
_PRRT_RIL:
        MOV   AL, [BX]
        TEST  AL, AL
        JZ    _PRRT_RIDN
        MOV   SI, BX
        MOV   DI, WORD PTR [BP-2]
_PRRT_RIC:
        MOV   AL, [DI]
        TEST  AL, AL
        JZ    _PRRT_RIOK
        MOV   AH, [SI]
        CMP   AL, AH
        JNE   _PRRT_RIN
        INC   SI
        INC   DI
        JMP   _PRRT_RIC
_PRRT_RIN:
        INC   BX
        INC   DX
        JMP   _PRRT_RIL
_PRRT_RIOK:
        MOV   AX, DX
        INC   BX
        INC   DX
        JMP   _PRRT_RIL
_PRRT_RIDN:
        POP   DX
        POP   BX
        POP   DI
        POP   SI
        ADD   SP, 2
        POP   BP
        RET
_PRRT_RINDEX ENDP

_PRRT_SUBSTR PROC NEAR
        PUSH  SI
        PUSH  DI
        PUSH  BX
        PUSH  CX
        TEST  BX, BX
        JZ    _PRRT_SUBST
_PRRT_SUBADV:
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_SUBEN
        INC   SI
        DEC   BX
        JNZ   _PRRT_SUBADV
_PRRT_SUBST:
_PRRT_SUBCPY:
        MOV   AL, [SI]
        TEST  AL, AL
        JZ    _PRRT_SUBEN
        CMP   CX, 0FFFFh
        JE    _PRRT_SUBND
        TEST  CX, CX
        JZ    _PRRT_SUBEN
        DEC   CX
_PRRT_SUBND:
        MOV   [DI], AL
        INC   SI
        INC   DI
        JMP   _PRRT_SUBCPY
_PRRT_SUBEN:
        MOV   BYTE PTR [DI], 0
        POP   CX
        POP   BX
        POP   DI
        POP   SI
        RET
_PRRT_SUBSTR ENDP

_PRRT_HEX2INT PROC NEAR
        PUSH  SI
        PUSH  BX
        XOR   AX, AX
        XOR   BX, BX
        MOV   BL, [SI]
        CMP   BL, 48
        JNE   _PRRT_HIL
        MOV   BL, [SI+1]
        CMP   BL, 120
        JE    _PRRT_HISKIP
        CMP   BL, 88
        JNE   _PRRT_HIL
_PRRT_HISKIP:
        INC   SI
        INC   SI
_PRRT_HIL:
        XOR   BX, BX
        MOV   BL, [SI]
        TEST  BL, BL
        JZ    _PRRT_HIDN
        CMP   BL, 48
        JL    _PRRT_HIDN
        CMP   BL, 57
        JLE   _PRRT_HIDIG
        CMP   BL, 65
        JL    _PRRT_HIDN
        CMP   BL, 70
        JLE   _PRRT_HIHEX
        CMP   BL, 97
        JL    _PRRT_HIDN
        CMP   BL, 102
        JG    _PRRT_HIDN
        SUB   BL, 87
        JMP   _PRRT_HIACC
_PRRT_HIHEX:
        SUB   BL, 55
        JMP   _PRRT_HIACC
_PRRT_HIDIG:
        SUB   BL, 48
_PRRT_HIACC:
        SHL   AX, 1
        SHL   AX, 1
        SHL   AX, 1
        SHL   AX, 1
        OR    AX, BX
        INC   SI
        JMP   _PRRT_HIL
_PRRT_HIDN:
        POP   BX
        POP   SI
        RET
_PRRT_HEX2INT ENDP

_PRRT_OCT2INT PROC NEAR
        PUSH  SI
        PUSH  BX
        XOR   AX, AX
_PRRT_OIL:
        XOR   BX, BX
        MOV   BL, [SI]
        TEST  BL, BL
        JZ    _PRRT_OIDN
        SUB   BL, 48
        JL    _PRRT_OIDN
        CMP   BL, 7
        JG    _PRRT_OIDN
        SHL   AX, 1
        SHL   AX, 1
        SHL   AX, 1
        OR    AX, BX
        INC   SI
        JMP   _PRRT_OIL
_PRRT_OIDN:
        POP   BX
        POP   SI
        RET
_PRRT_OCT2INT ENDP

_PRRT_READLINE PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  BX
        PUSH  SI
        PUSH  DI
        MOV   DI, OFFSET _PRRT_FHBUF
        MOV   SI, 0
_PRRT_RLL:
        CMP   SI, 0FEh
        JGE   _PRRT_RLDON
        MOV   BX, WORD PTR [BP-2]
        MOV   AH, 3Fh
        MOV   CX, 1
        MOV   DX, DI
        INT   21h
        JC    _PRRT_RLEOF
        TEST  AX, AX
        JZ    _PRRT_RLEOF
        MOV   AL, BYTE PTR [DI]
        CMP   AL, 0Ah
        JE    _PRRT_RLDON
        CMP   AL, 0Dh
        JE    _PRRT_RLDON
        INC   DI
        INC   SI
        JMP   _PRRT_RLL
_PRRT_RLEOF:
        TEST  SI, SI
        JZ    _PRRT_RLNUL
        JMP   _PRRT_RLDON
_PRRT_RLNUL:
        XOR   AX, AX
        JMP   _PRRT_RLRET
_PRRT_RLDON:
        MOV   BYTE PTR [DI], 0
        MOV   AX, OFFSET _PRRT_FHBUF
_PRRT_RLRET:
        POP   DI
        POP   SI
        POP   BX
        POP   BP
        RET
_PRRT_READLINE ENDP

_PRRT_STRLEN PROC NEAR
        PUSH  DI
        MOV   DI, SI
_PRRT_STL:
        MOV   AL, [DI]
        TEST  AL, AL
        JZ    _PRRT_STE
        INC   DI
        JMP   _PRRT_STL
_PRRT_STE:
        MOV   AX, DI
        SUB   AX, SI
        MOV   CX, AX
        POP   DI
        RET
_PRRT_STRLEN ENDP

_PRRT_PRINT PROC NEAR
        PUSH  AX
        PUSH  DX
        MOV   DX, SI
        MOV   AH, 40h
        INT   21h
        POP   DX
        POP   AX
        RET
_PRRT_PRINT ENDP

_PRRT_PRINTLN PROC NEAR
        PUSH  AX
        PUSH  SI
        PUSH  CX
        PUSH  DX
        MOV   SI, OFFSET _PRRT_CRLF
        MOV   DX, SI
        MOV   CX, 2
        MOV   AH, 40h
        INT   21h
        POP   DX
        POP   CX
        POP   SI
        POP   AX
        RET
_PRRT_PRINTLN ENDP

_PRRT_ITOA PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  BX
        PUSH  CX
        PUSH  DX
        PUSH  SI
        PUSH  DI
        TEST  AX, AX
        JGE   _PRRT_ITP
        NEG   AX
        MOV   BYTE PTR [DI], '-'
        INC   DI
_PRRT_ITP:
        MOV   SI, DI
        MOV   BX, 10
        XOR   CX, CX
_PRRT_ITDL:
        XOR   DX, DX
        DIV   BX
        ADD   DL, 48
        PUSH  DX
        INC   CX
        TEST  AX, AX
        JNZ   _PRRT_ITDL
_PRRT_ITRL:
        POP   DX
        MOV   [SI], DL
        INC   SI
        LOOP  _PRRT_ITRL
        MOV   BYTE PTR [SI], 0
        POP   DI
        POP   SI
        POP   DX
        POP   CX
        POP   BX
        POP   BP
        RET
_PRRT_ITOA ENDP

_PRRT_CONCAT PROC NEAR
        PUSH  AX
        PUSH  SI
        PUSH  DI
_PRRT_CCW:
        MOV   AL, [DI]
        TEST  AL, AL
        JZ    _PRRT_CCC
        INC   DI
        JMP   _PRRT_CCW
_PRRT_CCC:
        MOV   AL, [SI]
        MOV   [DI], AL
        TEST  AL, AL
        JZ    _PRRT_CCE
        INC   SI
        INC   DI
        JMP   _PRRT_CCC
_PRRT_CCE:
        POP   DI
        POP   SI
        POP   AX
        RET
_PRRT_CONCAT ENDP

_PRRT_STRREPEAT PROC NEAR
        PUSH  BP
        MOV   BP, SP
        PUSH  SI
        PUSH  DI
        PUSH  CX
        PUSH  BX
        PUSH  AX
        MOV   BYTE PTR [DI], 0
        TEST  CX, CX
        JZ    _PRRT_SRPE
        MOV   BX, DI
_PRRT_SRPL:
        MOV   SI, WORD PTR [BP-2]
_PRRT_SRCPY:
        MOV   AL, [SI]
        MOV   [BX], AL
        TEST  AL, AL
        JZ    _PRRT_SRD1
        INC   SI
        INC   BX
        JMP   _PRRT_SRCPY
_PRRT_SRD1:
        DEC   CX
        JNZ   _PRRT_SRPL
_PRRT_SRPE:
        POP   AX
        POP   BX
        POP   CX
        POP   DI
        POP   SI
        POP   BP
        RET
_PRRT_STRREPEAT ENDP

_PRRT_PUSH PROC NEAR
        PUSH  BX
        PUSH  CX
        MOV   CX, [SI]
        INC   CX
        MOV   BX, SI
        SHL   CX, 1
        ADD   BX, CX
        MOV   [BX], AX
        INC   WORD PTR [SI]
        POP   CX
        POP   BX
        RET
_PRRT_PUSH ENDP

_PRRT_PANIC PROC NEAR
        PUSH  DX
        CALL  _PRRT_STRLEN
        MOV   DX, SI
        MOV   BX, 2
        MOV   AH, 40h
        INT   21h
        POP   DX
        MOV   AX, 4C01h
        INT   21h
_PRRT_PANIC ENDP

_TEXT   ENDS

_DATA   SEGMENT WORD PUBLIC 'DATA'

_PRK_2:
        DB  'Bonjour Monde'0

_PRRX_P1:
        DB  'Bonjour'0

_PRK_5:
        DB  'trouve: Bonjour'10
        DB  0

_PRK_6:
        DB  'absent: Bonjour'10
        DB  0

_PRRX_P2:
        DB  'Monde'0

_PRK_9:
        DB  'trouve: Monde'10,0

_PRRX_P3:
        DB  'Adieu'0

_PRK_12:
        DB  'absent: Adieu'10,0

_PRK_14:
        DB  'user'3,'example'4,'.co'
        DB  'm'0

_PRRX_P4:
        DB  'example'0

_PRK_17:
        DB  'domaine example '
        DB  'detecte'10,0

_PRK_19:
        DB  'Hello World'0

_PRRX_P5:
        DB  'World'0

_PRRX_R5:
        DB  'Perl'0

_PRRT_IBUF:
        DW  8 DUP(0)

_PRK_23:
        DB  10,0

_PRK_25:
        DB  'foo bar foo'0

_PRRX_P6:
        DB  'foo'0

_PRRX_R6:
        DB  'baz'0

_PRK_30:
        DB  'http://www.examp'
        DB  'le.com'0

_PRRX_P7:
        DB  'http'0

_PRK_33:
        DB  'protocole http'10,0

_PRRX_P8:
        DB  'https'0

_PRK_36:
        DB  'pas https'10,0

_PRK_38:
        DB  'Jean Dupont'0

_PRRX_P9:
        DB  'Dupont'0

_PRRX_P10:
        DB  'Dupont'0

_PRRX_R10:
        DB  'Martin'0

_PRK_45:
        DB  'rien ici'0

_PRRX_P11:
        DB  'PERL86'0

_PRK_48:
        DB  'trouve PERL86'10,0

_PRK_49:
        DB  'PERL86 absent'10,0

_PRRT_FHBUF:
        DW  128 DUP(0)

_PRRT_CRLF:
        DB  13,10,0

_PRCAP_1:
        DW  0
_PRCAP_2:
        DW  0

_DATA   ENDS

        END     _PRF_main
